// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type BodyResult struct {
	Path     *string `json:"path,omitempty"`
	Normal   *bool   `json:"normal,omitempty"`
	Expected *string `json:"expected,omitempty"`
	Actual   *string `json:"actual,omitempty"`
}

type DepMetaResult struct {
	Normal   *bool   `json:"normal,omitempty"`
	Key      *string `json:"key,omitempty"`
	Expected *string `json:"expected,omitempty"`
	Actual   *string `json:"actual,omitempty"`
}

type DepResult struct {
	Name *string          `json:"name,omitempty"`
	Type *DependencyType  `json:"type,omitempty"`
	Meta []*DepMetaResult `json:"meta,omitempty"`
}

type Dependency struct {
	Name *string         `json:"name,omitempty"`
	Type *DependencyType `json:"type,omitempty"`
	Meta *MetaKeyValue   `json:"meta,omitempty"`
	Data *string         `json:"data,omitempty"`
}

type FormData struct {
	Key    *string   `json:"key,omitempty"`
	Values []*string `json:"values,omitempty"`
	Paths  []*string `json:"paths,omitempty"`
}

type GrpcReq struct {
	Body   *string `json:"body,omitempty"`
	Method *string `json:"method,omitempty"`
}

type GrpcResp struct {
	Body  *string `json:"body,omitempty"`
	Error *string `json:"error,omitempty"`
}

type Header struct {
	Key   *string   `json:"key,omitempty"`
	Value []*string `json:"value,omitempty"`
}

type HeaderResult struct {
	Normal   *bool   `json:"normal,omitempty"`
	Expected *Header `json:"expected,omitempty"`
	Actual   *Header `json:"actual,omitempty"`
}

type HTTPReq struct {
	Method     *Method     `json:"method,omitempty"`
	ProtoMajor *int        `json:"protoMajor,omitempty"`
	ProtoMinor *int        `json:"protoMinor,omitempty"`
	URL        *string     `json:"url,omitempty"`
	URLParams  []*Kv       `json:"urlParams,omitempty"`
	Header     []*Kv       `json:"header,omitempty"`
	Body       *string     `json:"body,omitempty"`
	BodyType   *string     `json:"bodyType,omitempty"`
	Binary     *string     `json:"binary,omitempty"`
	Form       []*FormData `json:"form,omitempty"`
}

type HTTPResp struct {
	StatusCode    *int    `json:"statusCode,omitempty"`
	Header        []*Kv   `json:"header,omitempty"`
	Body          *string `json:"body,omitempty"`
	BodyType      *string `json:"bodyType,omitempty"`
	StatusMessage *string `json:"statusMessage,omitempty"`
	ProtoMajor    *int    `json:"protoMajor,omitempty"`
	ProtoMinor    *int    `json:"protoMinor,omitempty"`
	Binary        *string `json:"binary,omitempty"`
}

type IntResult struct {
	Normal   *bool `json:"normal,omitempty"`
	Expected *int  `json:"expected,omitempty"`
	Actual   *int  `json:"actual,omitempty"`
}

type Kv struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type MetaKeyValue struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Mock struct {
	Version *Version `json:"version,omitempty"`
	Kind    *Kind    `json:"kind,omitempty"`
	Name    *string  `json:"name,omitempty"`
	Spec    *string  `json:"spec,omitempty"`
}

type Result struct {
	StatusCode    *IntResult      `json:"statusCode,omitempty"`
	HeadersResult []*HeaderResult `json:"headersResult,omitempty"`
	BodyResult    []*BodyResult   `json:"bodyResult,omitempty"`
	DepResult     []*DepResult    `json:"depResult,omitempty"`
}

type Test struct {
	ID         *string       `json:"id,omitempty"`
	Status     *TestStatus   `json:"status,omitempty"`
	Started    *string       `json:"started,omitempty"`
	Completed  *string       `json:"completed,omitempty"`
	RunID      *string       `json:"runId,omitempty"`
	TestCaseID *string       `json:"testCaseId,omitempty"`
	URI        *string       `json:"uri,omitempty"`
	Dep        []*Dependency `json:"dep,omitempty"`
	Mocks      []*string     `json:"mocks,omitempty"`
	Req        *HTTPReq      `json:"req,omitempty"`
	HTTPResp   *HTTPResp     `json:"http_resp,omitempty"`
	Noise      []*string     `json:"noise,omitempty"`
	Result     *Result       `json:"result,omitempty"`
	GrpcReq    *GrpcReq      `json:"grpc_req,omitempty"`
	GrpcResp   *GrpcResp     `json:"grpc_resp,omitempty"`
}

type TestCase struct {
	ID       *string       `json:"id,omitempty"`
	Created  *string       `json:"created,omitempty"`
	Updated  *string       `json:"updated,omitempty"`
	Captured *string       `json:"captured,omitempty"`
	Cid      *string       `json:"cid,omitempty"`
	AppID    *string       `json:"appID,omitempty"`
	URI      *string       `json:"uri,omitempty"`
	HTTPReq  *HTTPReq      `json:"httpReq,omitempty"`
	HTTPResp *HTTPResp     `json:"httpResp,omitempty"`
	GrpcReq  *GrpcReq      `json:"grpcReq,omitempty"`
	GrpcResp *GrpcResp     `json:"grpcResp,omitempty"`
	Deps     []*Dependency `json:"deps,omitempty"`
	AllKeys  []*Kv         `json:"allKeys,omitempty"`
	Anchors  []*Kv         `json:"anchors,omitempty"`
	Noise    []string      `json:"noise,omitempty"`
	Mocks    []*Mock       `json:"mocks,omitempty"`
	Type     *string       `json:"type,omitempty"`
}

type TestReport struct {
	ID           *string  `json:"id,omitempty"`
	Version      *Version `json:"version,omitempty"`
	Kind         *Kind    `json:"kind,omitempty"`
	Name         *string  `json:"name,omitempty"`
	Status       *string  `json:"status,omitempty"`
	Success      *int     `json:"success,omitempty"`
	Completed    *int     `json:"completed,omitempty"`
	Started      *int     `json:"started,omitempty"`
	Failure      *int     `json:"failure,omitempty"`
	Total        *int     `json:"total,omitempty"`
	TestCasePath *string  `json:"testCasePath,omitempty"`
	MockPath     *string  `json:"mockPath,omitempty"`
	Tests        []*Test  `json:"tests,omitempty"`
}

type TestSuite struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

type DependencyType string

const (
	DependencyTypeNoSQLDb    DependencyType = "NoSqlDB"
	DependencyTypeSQLDb      DependencyType = "SqlDB"
	DependencyTypeGrpc       DependencyType = "GRPC"
	DependencyTypeHTTPClient DependencyType = "HttpClient"
)

var AllDependencyType = []DependencyType{
	DependencyTypeNoSQLDb,
	DependencyTypeSQLDb,
	DependencyTypeGrpc,
	DependencyTypeHTTPClient,
}

func (e DependencyType) IsValid() bool {
	switch e {
	case DependencyTypeNoSQLDb, DependencyTypeSQLDb, DependencyTypeGrpc, DependencyTypeHTTPClient:
		return true
	}
	return false
}

func (e DependencyType) String() string {
	return string(e)
}

func (e *DependencyType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DependencyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DependencyType", str)
	}
	return nil
}

func (e DependencyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Kind string

const (
	KindHTTP       Kind = "HTTP"
	KindGeneric    Kind = "GENERIC"
	KindSQL        Kind = "SQL"
	KindGrpcExport Kind = "GRPC_EXPORT"
)

var AllKind = []Kind{
	KindHTTP,
	KindGeneric,
	KindSQL,
	KindGrpcExport,
}

func (e Kind) IsValid() bool {
	switch e {
	case KindHTTP, KindGeneric, KindSQL, KindGrpcExport:
		return true
	}
	return false
}

func (e Kind) String() string {
	return string(e)
}

func (e *Kind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Kind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Kind", str)
	}
	return nil
}

func (e Kind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Method string

const (
	MethodGet     Method = "GET"
	MethodPut     Method = "PUT"
	MethodHead    Method = "HEAD"
	MethodPost    Method = "POST"
	MethodPatch   Method = "PATCH"
	MethodDelete  Method = "DELETE"
	MethodOptions Method = "OPTIONS"
	MethodTrace   Method = "TRACE"
)

var AllMethod = []Method{
	MethodGet,
	MethodPut,
	MethodHead,
	MethodPost,
	MethodPatch,
	MethodDelete,
	MethodOptions,
	MethodTrace,
}

func (e Method) IsValid() bool {
	switch e {
	case MethodGet, MethodPut, MethodHead, MethodPost, MethodPatch, MethodDelete, MethodOptions, MethodTrace:
		return true
	}
	return false
}

func (e Method) String() string {
	return string(e)
}

func (e *Method) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Method(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Method", str)
	}
	return nil
}

func (e Method) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TestStatus string

const (
	TestStatusPending TestStatus = "Pending"
	TestStatusRunning TestStatus = "Running"
	TestStatusFailed  TestStatus = "Failed"
	TestStatusPassed  TestStatus = "Passed"
)

var AllTestStatus = []TestStatus{
	TestStatusPending,
	TestStatusRunning,
	TestStatusFailed,
	TestStatusPassed,
}

func (e TestStatus) IsValid() bool {
	switch e {
	case TestStatusPending, TestStatusRunning, TestStatusFailed, TestStatusPassed:
		return true
	}
	return false
}

func (e TestStatus) String() string {
	return string(e)
}

func (e *TestStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TestStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TestStatus", str)
	}
	return nil
}

func (e TestStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Version string

const (
	VersionV1Beta1 Version = "V1Beta1"
	VersionV1Beta2 Version = "V1Beta2"
)

var AllVersion = []Version{
	VersionV1Beta1,
	VersionV1Beta2,
}

func (e Version) IsValid() bool {
	switch e {
	case VersionV1Beta1, VersionV1Beta2:
		return true
	}
	return false
}

func (e Version) String() string {
	return string(e)
}

func (e *Version) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Version(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Version", str)
	}
	return nil
}

func (e Version) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
