repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2

- repo: https://github.com/golangci/golangci-lint
  rev: v2.1.2
  hooks:
    - id: golangci-lint