package schema

import (
	"testing"

	"go.keploy.io/server/v3/pkg/models"
	"go.uber.org/zap"
)

// opWithNumericField builds an operation whose request and response each carry a
// single numeric property of the given OpenAPI type, imitating a contract
// generated by one keploy version.
func opWithNumericField(typ string) *models.Operation {
	props := func() map[string]map[string]interface{} {
		return map[string]map[string]interface{}{"id": {"type": typ}}
	}
	return &models.Operation{
		RequestBody: &models.RequestBody{
			Content: map[string]models.MediaType{
				"application/json": {Schema: models.Schema{Type: "object", Properties: props()}},
			},
		},
		Responses: map[string]models.ResponseItem{
			"200": {Content: map[string]models.MediaType{
				"application/json": {Schema: models.Schema{Type: "object", Properties: props()}},
			}},
		},
	}
}

func docWith(op *models.Operation) models.OpenAPI {
	return models.OpenAPI{
		OpenAPI: "3.0.0",
		Info:    models.Info{Title: "t", Version: "v"},
		Paths:   map[string]models.PathItem{"/users": {Post: op}},
	}
}

// TestMatch_IntegerNumberSkewStillMatches is the behaviour test for the
// cross-version problem, as opposed to a unit test on the type helper.
//
// A provider on a keploy that predates integer inference ships {"type":"number"}
// where a consumer on a newer keploy generates {"type":"integer"} for the same
// field. `keploy contract download` copies the provider's schema verbatim rather
// than regenerating it, so both spellings legitimately coexist. Scoring that as
// a mismatch reports the mock MISSED - a false failure caused purely by version
// skew, and it bites request bodies first because compareRequestBodies gates the
// candidate before scoring ever runs.
func TestMatch_IntegerNumberSkewStillMatches(t *testing.T) {
	tests := []struct {
		name      string
		mockType  string
		testType  string
		wantScore float64
		wantPass  bool
	}{
		{name: "old number mock vs new integer test", mockType: "number", testType: "integer", wantScore: 1, wantPass: true},
		{name: "new integer mock vs old number test", mockType: "integer", testType: "number", wantScore: 1, wantPass: true},
		{name: "same version number", mockType: "number", testType: "number", wantScore: 1, wantPass: true},
		{name: "same version integer", mockType: "integer", testType: "integer", wantScore: 1, wantPass: true},
		// A genuinely different type must still be rejected: -1 is
		// NOTCANDIDATE, i.e. compareRequestBodies gated the mock out.
		{name: "number vs string is still rejected", mockType: "number", testType: "string", wantScore: -1, wantPass: false},
		{name: "integer vs string is still rejected", mockType: "integer", testType: "string", wantScore: -1, wantPass: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Absolute expectations, deliberately not a comparison against a
			// same-version baseline computed in the same process: a baseline
			// shifts with any regression that affects both sides, so it would
			// mask exactly the mock-side bugs this test exists to catch.
			got, pass, err := Match(docWith(opWithNumericField(tt.mockType)), docWith(opWithNumericField(tt.testType)),
				"test-set-0", "mock-set-0", zap.NewNop(), models.IdentifyMode)
			if err != nil {
				t.Fatalf("Match failed: %v", err)
			}
			if got != tt.wantScore {
				t.Errorf("score = %v, want %v", got, tt.wantScore)
			}
			if pass != tt.wantPass {
				t.Errorf("pass = %v, want %v", pass, tt.wantPass)
			}
		})
	}
}
