name: 'Setup Private Parsers'
description: 'Sets up Go, loads an SSH key, fetches private Go dependencies, and creates the extraparsers.go file.'

inputs:
  ssh-private-key:
    description: 'The private SSH deploy key for the integrations repository.'
    required: true
  go-cache:
    description: 'Whether to enable Go module caching (default: true).'
    required: false
    default: true
  integration-ref:
    description: 'The git ref (branch, tag, or commit) of the integrations repo.'
    required: true
    default: 'main'

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.24"
        cache: ${{ inputs.go-cache }}

    - name: Start ssh-agent and add key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Trust github.com host key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Force GitHub over SSH (no stray spaces!)
      shell: bash
      run: |
        git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
        git config --global url."ssh://git@github.com/".insteadOf "http://github.com/"

    - name: Configure Go for private modules
      shell: bash
      run: |
        go env -w GOPRIVATE=github.com/keploy/*
        go env -w GONOSUMDB=github.com/keploy/*

    - name: Fetch private integrations dependency & create parsers file
      shell: bash
      env:
        INTEGRATION_REF: ${{ inputs.integration-ref }}
      run: |
        echo "Downloading github.com/keploy/integrations@${INTEGRATION_REF:-main}"
        # go get can modify go.mod; for a pure fetch use go mod download:
        go mod download github.com/keploy/integrations@${INTEGRATION_REF:-main}

        echo "Creating extraparsers.go..."
        mkdir -p pkg/agent/proxy
        cat > pkg/agent/proxy/extraparsers.go <<'EOF'
        //go:build linux
        package proxy

        import (
        	_ "github.com/keploy/integrations/pkg/parsers"
        )
        EOF

    - name: Tidy modules
      shell: bash
      run: go mod tidy
