name: 'Setup Private Parsers'
description: 'Sets up Go, loads an SSH key, fetches private Go dependencies, and creates the extraparsers.go file.'

inputs:
  ssh-private-key:
    description: 'The private SSH deploy key for the integrations repository.'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.24"

    - name: Load Private SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    # ---------------- Windows ----------------
    - name: Configure Git/SSH and Fetch Integrations (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Ensure ~/.ssh exists for the service account (e.g., NetworkService)
        $sshDir = "$env:USERPROFILE\.ssh"
        New-Item -ItemType Directory -Force -Path $sshDir | Out-Null

        # Trust GitHub host keys (fixes "Host key verification failed")
        ssh-keyscan -t rsa,ecdsa,ed25519 github.com | Out-File -FilePath "$sshDir\known_hosts" -Encoding ascii -Append

        # Use SSH for any github.com URL
        git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

        # (Optional) be lenient on first connection
        git config --global core.sshCommand "ssh -o StrictHostKeyChecking=yes"

        # Tell Go these are private modules (no proxy/sumdb)
        go env -w GOPRIVATE=github.com/keploy/*
        go env -w GONOSUMDB=github.com/keploy/*

        Write-Host "Fetching private integrations dependency via SSH..."
        go get github.com/keploy/integrations

        Write-Host "Creating extraparsers.go..."
        New-Item -ItemType Directory -Force -Path pkg/core/proxy | Out-Null
        @'
        //go:build linux

        package proxy

        import (
          _ "github.com/keploy/integrations/pkg/parsers"
        )
        '@ | Set-Content pkg/core/proxy/extraparsers.go -NoNewline

        Write-Host "Tidying up Go modules..."
        go mod tidy

    # ---------------- Linux/macOS ----------------
    - name: Configure Git/SSH and Fetch Integrations (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$HOME/.ssh"
        ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> "$HOME/.ssh/known_hosts"

        git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
        export GOPRIVATE=github.com/keploy/*
        export GONOSUMDB=github.com/keploy/*

        echo "Fetching private integrations dependency via SSH..."
        go get github.com/keploy/integrations

        echo "Creating extraparsers.go..."
        mkdir -p pkg/core/proxy
        cat > pkg/core/proxy/extraparsers.go <<'EOF'
        //go:build linux

        package proxy

        import (
          _ "github.com/keploy/integrations/pkg/parsers"
        )
        EOF

        echo "Tidying up Go modules..."
        go mod tidy
