name: 'Setup Private Parsers'
description: 'Sets up Go, loads an SSH key, fetches private Go dependencies, and creates the extraparsers.go file.'

inputs:
  ssh-private-key:
    description: 'The private SSH deploy key for the integrations repository.'
    required: true
  go-cache:
    description: 'Whether to enable Go module caching (default: true).'
    required: false
    default: true
  integration-ref:
    description: 'The git ref (branch, tag, or commit) of the integrations repo.'
    required: true
    default: 'main'

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.24"
        cache: ${{ inputs.go-cache }}

    - name: Add GitHub to known hosts (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Add GitHub to known hosts (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $sshDir = Join-Path $Env:USERPROFILE ".ssh"
        New-Item -ItemType Directory -Path $sshDir -Force | Out-Null
        ssh-keyscan github.com | Out-File -FilePath (Join-Path $sshDir "known_hosts") -Encoding ascii -Append

    - name: Load Private SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Configure Git, Fetch Dependencies, and Create Parsers File (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      env:
        INTEGRATION_REF: ${{ inputs.integration-ref }}
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
        
        echo "Fetching private integrations dependency via SSH..."
        GOPRIVATE=github.com/keploy/integrations go get github.com/keploy/integrations@${{ inputs.integration-ref }}
        
        echo "Creating extraparsers.go..."
        mkdir -p pkg/agent/proxy
        cat <<'EOF' > pkg/agent/proxy/extraparsers.go
        //go:build linux

        package proxy

        import (
        	_ "github.com/keploy/integrations/pkg/parsers"
        )
        EOF
    - name: Configure Git, Fetch Dependencies, and Create Parsers File (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        INTEGRATION_REF: ${{ inputs.integration-ref }}
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"

        Write-Host "Fetching private integrations dependency via SSH..."
        $env:GOPRIVATE = "github.com/keploy/integrations"
        go get "github.com/keploy/integrations@${{ inputs.integration-ref }}"

        Write-Host "Creating extraparsers.go..."
        New-Item -ItemType Directory -Path "pkg/agent/proxy" -Force | Out-Null
        @"
//go:build linux

package proxy

import (
	_ "github.com/keploy/integrations/pkg/parsers"
)
"@ | Set-Content -Path "pkg/agent/proxy/extraparsers.go" -Encoding UTF8

    - name: Add any missing Go modules (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "Tidying up Go modules..."
        go mod tidy
    - name: Add any missing Go modules (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write-Host "Tidying up Go modules..."
        go mod tidy
