name: 'Setup Private Parsers'
description: 'Sets up Go, loads an SSH key, fetches private Go dependencies, and creates the extraparsers.go file.'

inputs:
  ssh-private-key:
    description: 'The private SSH deploy key for the integrations repository.'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.24"

    - name: Load Private SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Configure Git, Fetch Dependencies, and Create Parsers File
      shell: bash
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
        
        echo "Fetching private integrations dependency via SSH..."
        GOPRIVATE=github.com/keploy/integrations go get github.com/keploy/integrations
        
        echo "Creating extraparsers.go..."
        mkdir -p pkg/core/proxy
        cat <<'EOF' > pkg/core/proxy/extraparsers.go
        //go:build linux

        package proxy

        import (
        	_ "github.com/keploy/integrations/pkg/parsers"
        )
        EOF
