name: 'Setup Private Parsers'
description: 'Sets up Go, loads an SSH key, fetches private Go dependencies, and creates the extraparsers.go file.'

inputs:
  ssh-private-key:
    description: 'The private SSH deploy key for the integrations repository.'
    required: true
  go-cache:
    description: 'Whether to enable Go module caching (default: true).'
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.24"
        cache: ${{ inputs.go-cache }}

    - name: Load Private SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Configure Git, Fetch Dependencies, and Create Parsers File
      shell: bash
      run: |
        set -euo pipefail
        git config --global url."git@github.com:".insteadOf "https://github.com/"
        
        echo "Fetching latest commit hash from v2 branch..."
        LATEST_COMMIT=$(git ls-remote https://github.com/keploy/integrations.git refs/heads/fix/fuzzer-mongo | awk '{print $1}')
        if [ -z "$LATEST_COMMIT" ]; then
          echo "Error: Failed to fetch latest commit hash from v2 branch"
          exit 1
        fi
        echo "Latest commit hash: $LATEST_COMMIT"
        
        echo "Fetching private integrations dependency via SSH..."
        GOPRIVATE=github.com/keploy/integrations go get github.com/keploy/integrations@$LATEST_COMMIT
        
        echo "Creating extraparsers.go..."
        mkdir -p pkg/core/proxy
        cat <<'EOF' > pkg/core/proxy/extraparsers.go
        //go:build linux

        package proxy

        import (
        	_ "github.com/keploy/integrations/pkg/parsers"
        )
        EOF
    - name: Add any missing Go modules
      shell: bash
      run: |
        echo "Tidying up Go modules..."
        go mod tidy    