package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"go.keploy.io/server/v2/pkg/graph"
	"go.keploy.io/server/v2/pkg/graph/model"
)

// RunTestSet is the resolver for the runTestSet field.
func (r *mutationResolver) RunTestSet(ctx context.Context, testSetID string, testRunID string, appID int) (bool, error) {
	panic(fmt.Errorf("not implemented: RunTestSet - runTestSet"))
}

// StartHooks is the resolver for the startHooks field.
func (r *mutationResolver) StartHooks(ctx context.Context) (*model.TestRunInfo, error) {
	panic(fmt.Errorf("not implemented: StartHooks - startHooks"))
}

// StartApp is the resolver for the startApp field.
func (r *mutationResolver) StartApp(ctx context.Context, appID int) (bool, error) {
	panic(fmt.Errorf("not implemented: StartApp - startApp"))
}

// StopHooks is the resolver for the stopHooks field.
func (r *mutationResolver) StopHooks(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: StopHooks - stopHooks"))
}

// StopApp is the resolver for the stopApp field.
func (r *mutationResolver) StopApp(ctx context.Context, appID int) (bool, error) {
	panic(fmt.Errorf("not implemented: StopApp - stopApp"))
}

// NormaliseTc is the resolver for the normaliseTc field.
func (r *mutationResolver) NormaliseTc(ctx context.Context, normalize model.NormalizeInput) (*model.NormaliseOutput, error) {
	panic(fmt.Errorf("not implemented: NormaliseTc - normaliseTc"))
}

// DenoiseTestCase is the resolver for the denoiseTestCase field.
func (r *mutationResolver) DenoiseTestCase(ctx context.Context, noise model.NoiseInput) (*model.NoiseOutput, error) {
	panic(fmt.Errorf("not implemented: DenoiseTestCase - denoiseTestCase"))
}

// TestSets is the resolver for the testSets field.
func (r *queryResolver) TestSets(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: TestSets - testSets"))
}

// TestSetStatus is the resolver for the testSetStatus field.
func (r *queryResolver) TestSetStatus(ctx context.Context, testRunID string, testSetID string) (*model.TestSetStatus, error) {
	panic(fmt.Errorf("not implemented: TestSetStatus - testSetStatus"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
