package cli

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"go.keploy.io/server/v3/cli/provider"
	"go.keploy.io/server/v3/config"
	"go.uber.org/zap"
)

// A factory that fails, deliberately: `config --generate` pings telemetry
// through the service lookup but needs nothing from it, so a lookup that
// cannot be satisfied must not stop the write.
type failingFactory struct{}

func (failingFactory) GetService(context.Context, string) (interface{}, error) {
	return nil, errors.New("no services in a unit test")
}

// The REAL configurator, so the flags under test are the ones the binary
// registers -- a stub would only prove the test agrees with itself.
func realConfigCmd(t *testing.T) *cobra.Command {
	t.Helper()
	cfg := config.New()
	c := Config(context.Background(), zap.NewNop(), cfg, failingFactory{}, provider.NewCmdConfigurator(zap.NewNop(), cfg))
	if c == nil {
		t.Fatal("the config command could not be built")
	}
	c.SetOut(&bytes.Buffer{})
	c.SetErr(&bytes.Buffer{})
	return c
}

// `keploy config --generate` over a file that already exists.
//
// The guard used to be `!cfg.InCi`, reading a config.Config nothing ever
// writes to -- and `config` never registered --in-ci either, so there was no
// way to set it. In CI the prompt was asked anyway, stdin answered EOF,
// AskForConfirmation declined, and the command logged "Skipping" and exited
// 0: a pipeline step that regenerates the config recorded a success for
// having written nothing.
//
// `go test` has no terminal on stdin, so this runs in exactly the conditions
// CI does.
func TestConfigGenerate_RefusesToOverwriteWithNobodyToAsk(t *testing.T) {
	dir := t.TempDir()
	existing := filepath.Join(dir, "keploy.yml")
	const mine = "# hand written, do not lose me\ncommand: go test ./...\n"
	if err := os.WriteFile(existing, []byte(mine), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := realConfigCmd(t)
	cmd.SetArgs([]string{"--generate", "--path", dir})
	err := cmd.Execute()
	if err == nil {
		t.Fatal("it reported success; in CI that is a regenerate step that quietly did nothing")
	}
	// The refusal has to name the way through, or it is just a wall.
	if !strings.Contains(err.Error(), "--force") {
		t.Errorf("the refusal does not say how to get past it: %v", err)
	}
	if got, _ := os.ReadFile(existing); string(got) != mine {
		t.Errorf("it refused AND overwrote the file:\n%s", got)
	}
}

// ...and --force is that way through.
func TestConfigGenerate_ForceOverwrites(t *testing.T) {
	dir := t.TempDir()
	existing := filepath.Join(dir, "keploy.yml")
	if err := os.WriteFile(existing, []byte("# hand written\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := realConfigCmd(t)
	cmd.SetArgs([]string{"--generate", "--path", dir, "--force"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("--force did not get through: %v", err)
	}
	got, err := os.ReadFile(existing)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "hand written") {
		t.Fatal("--force left the old file in place")
	}
	if !strings.Contains(string(got), "# Generated by Keploy") {
		t.Errorf("what --force wrote is not a generated config:\n%s", got)
	}
}

// Nothing in the way: the ordinary first run still writes.
func TestConfigGenerate_WritesWhenThereIsNoFile(t *testing.T) {
	dir := t.TempDir()
	cmd := realConfigCmd(t)
	cmd.SetArgs([]string{"--generate", "--path", dir})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("a first generate failed: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "keploy.yml")); err != nil {
		t.Fatalf("no config was written: %v", err)
	}
}

// `keploy config defaults` is where every setting a generated config leaves
// out stays readable. It is attached with one AddCommand line that nothing
// else would miss if it were deleted.
func TestConfigCommand_CarriesTheDefaultsSubcommand(t *testing.T) {
	cmd := realConfigCmd(t)
	var names []string
	for _, sub := range cmd.Commands() {
		names = append(names, sub.Name())
	}
	found := false
	for _, n := range names {
		if n == "defaults" {
			found = true
		}
	}
	if !found {
		t.Fatalf("`keploy config defaults` is not attached; subcommands: %v", names)
	}
	// The flags the help text promises, from the real registry.
	for _, f := range []string{"generate", "path", "force"} {
		if cmd.Flags().Lookup(f) == nil {
			t.Errorf("--%s is not registered on `keploy config`", f)
		}
	}
	// Defaults, pinned: --generate and --force are consent, and consent that
	// defaults to true is not consent.
	for _, f := range []string{"generate", "force"} {
		flag := cmd.Flags().Lookup(f)
		if flag == nil {
			// Fatal, not Errorf: the loop above reported this non-fatally and
			// then this line dereferenced the nil, panicking the whole test
			// binary and taking every other test in ./cli with it.
			t.Fatalf("--%s is not registered, so its default cannot be checked", f)
		}
		if got := flag.DefValue; got != "false" {
			t.Errorf("--%s defaults to %q; it overwrites a developer's file without being asked for", f, got)
		}
	}
}

// Consent is about the file that will actually be REPLACED.
//
// A keploy.yml that is a link to the developer's hand-written config was
// treated as "not a file anyone wants kept" and skipped the gate entirely,
// while the writer followed the link and replaced what was on the other end:
// uncontrolled data loss, exit 0, and interactively not even a prompt. The
// identical file reached directly was correctly refused, so the link was the
// only difference.
func TestConfigGenerate_ALinkedConfigIsStillSomebodysFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "config"), 0o755); err != nil {
		t.Fatal(err)
	}
	real := filepath.Join(dir, "config", "keploy.yml")
	const mine = "# hand written, do not lose me\ncommand: go test ./...\n"
	if err := os.WriteFile(real, []byte(mine), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join("config", "keploy.yml"), filepath.Join(dir, "keploy.yml")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}

	cmd := realConfigCmd(t)
	cmd.SetArgs([]string{"--generate", "--path", dir})
	err := cmd.Execute()
	if got, _ := os.ReadFile(real); string(got) != mine {
		t.Fatalf("a hand-written config was destroyed through a link, unasked:\n%s", got)
	}
	if err == nil {
		t.Fatal("it reported success without writing and without asking")
	}
	if !strings.Contains(err.Error(), "--force") {
		t.Errorf("the refusal does not say how to get past it: %v", err)
	}

	// ...and --force goes through the link, to the file it names.
	cmd2 := realConfigCmd(t)
	cmd2.SetArgs([]string{"--generate", "--path", dir, "--force"})
	if err := cmd2.Execute(); err != nil {
		t.Fatalf("--force was refused: %v", err)
	}
	got, err := os.ReadFile(real)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "# Generated by Keploy") {
		t.Errorf("--force did not write through the link:\n%s", got)
	}
}
