name: pull-image
description: "Pull Image"
inputs:
  image_tag:
    description: "Docker image tag or digest to pull"
    required: false
    default: ttl.sh/keploy/keploy:1h
  version:
    description: "Version string to tag the pulled image with"
    required: false
    default: 3-dev
runs:
  using: composite
  steps:
    - name: Pull Image (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        IMAGE_REF="${{ inputs.image_tag }}"
        echo "Pulling ${IMAGE_REF} ..."
        docker pull "${IMAGE_REF}"

        # Retag to the name your stack expects
        # Works for both tag refs and digest refs
        docker tag "${IMAGE_REF}" ghcr.io/keploy/keploy:v${{ inputs.version }}
        docker images | awk 'NR==1 || /keploy\/keploy/ {print}'

    - name: Pull Image (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $IMAGE_REF = "${{ inputs.image_tag }}"

        Write-Host "Ensuring Docker is running..."

        try { wsl --shutdown } catch {}

        Get-Service docker -ErrorAction SilentlyContinue |
          Where-Object {$_.Status -ne "Running"} |
          Start-Service

        Write-Host "Waiting for Docker engine..."

        for ($i = 0; $i -lt 60; $i++) {
          try {
            docker info | Out-Null
            docker system info | Out-Null
            docker image ls | Out-Null
            break
          } catch {
            Start-Sleep 3
          }
        }

        Write-Host "Pulling $IMAGE_REF ..."

        for ($i = 0; $i -lt 5; $i++) {
          try {
            docker pull $IMAGE_REF
            break
          } catch {
            Write-Host "Pull failed, retrying..."
            Start-Sleep 5
          }
        }

        docker tag $IMAGE_REF ghcr.io/keploy/keploy:v${{ inputs.version }}
        docker images --format "{{.Repository}}:{{.Tag}}" | Select-String -Pattern "keploy/keploy" -SimpleMatch
