name: pull-image
description: "Pull Image"
inputs:
  image_tag:
    description: "Docker image tag or digest to pull"
    required: false
    default: ttl.sh/keploy/keploy:1h
runs:
  using: composite
  steps:
    - name: Pull Image
      shell: bash
      run: |
        set -euo pipefail
        IMAGE_REF="${{ inputs.image_tag }}"
        echo "Pulling ${IMAGE_REF} ..."
        docker pull "${IMAGE_REF}"

        # Retag to the name your stack expects
        # Works for both tag refs and digest refs
        docker tag "${IMAGE_REF}" ghcr.io/keploy/keploy:v2-dev
        docker images | awk 'NR==1 || /keploy\/keploy/ {print}'