// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package cbshim

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cbshimLibpqRangeKey struct {
	_   structs.HostLayout
	Pid uint32
	Idx uint32
}

type cbshimLibpqRangeVal struct {
	_     structs.HostLayout
	Start uint64
	End   uint64
}

// loadCbshim returns the embedded CollectionSpec for cbshim.
func loadCbshim() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CbshimBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cbshim: %w", err)
	}

	return spec, err
}

// loadCbshimObjects loads cbshim and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cbshimObjects
//	*cbshimPrograms
//	*cbshimMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCbshimObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCbshim()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cbshimSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cbshimSpecs struct {
	cbshimProgramSpecs
	cbshimMapSpecs
	cbshimVariableSpecs
}

// cbshimProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cbshimProgramSpecs struct {
	CbX509DigestEntry  *ebpf.ProgramSpec `ebpf:"cb_x509_digest_entry"`
	CbX509DigestReturn *ebpf.ProgramSpec `ebpf:"cb_x509_digest_return"`
}

// cbshimMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cbshimMapSpecs struct {
	Cbmap               *ebpf.MapSpec `ebpf:"cbmap"`
	Counters            *ebpf.MapSpec `ebpf:"counters"`
	LibpqRanges         *ebpf.MapSpec `ebpf:"libpq_ranges"`
	Pending             *ebpf.MapSpec `ebpf:"pending"`
	TargetNamespacePids *ebpf.MapSpec `ebpf:"target_namespace_pids"`
}

// cbshimVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cbshimVariableSpecs struct {
}

// cbshimObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCbshimObjects or ebpf.CollectionSpec.LoadAndAssign.
type cbshimObjects struct {
	cbshimPrograms
	cbshimMaps
	cbshimVariables
}

func (o *cbshimObjects) Close() error {
	return _CbshimClose(
		&o.cbshimPrograms,
		&o.cbshimMaps,
	)
}

// cbshimMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCbshimObjects or ebpf.CollectionSpec.LoadAndAssign.
type cbshimMaps struct {
	Cbmap               *ebpf.Map `ebpf:"cbmap"`
	Counters            *ebpf.Map `ebpf:"counters"`
	LibpqRanges         *ebpf.Map `ebpf:"libpq_ranges"`
	Pending             *ebpf.Map `ebpf:"pending"`
	TargetNamespacePids *ebpf.Map `ebpf:"target_namespace_pids"`
}

func (m *cbshimMaps) Close() error {
	return _CbshimClose(
		m.Cbmap,
		m.Counters,
		m.LibpqRanges,
		m.Pending,
		m.TargetNamespacePids,
	)
}

// cbshimVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCbshimObjects or ebpf.CollectionSpec.LoadAndAssign.
type cbshimVariables struct {
}

// cbshimPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCbshimObjects or ebpf.CollectionSpec.LoadAndAssign.
type cbshimPrograms struct {
	CbX509DigestEntry  *ebpf.Program `ebpf:"cb_x509_digest_entry"`
	CbX509DigestReturn *ebpf.Program `ebpf:"cb_x509_digest_return"`
}

func (p *cbshimPrograms) Close() error {
	return _CbshimClose(
		p.CbX509DigestEntry,
		p.CbX509DigestReturn,
	)
}

func _CbshimClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cbshim_arm64_bpfel.o
var _CbshimBytes []byte
