---
name: Documentation request
about: Suggest an improvement/addition in the Keploy Server Docs.
title: Docs
labels: Docs

---

**What does the current documentation state?**
Copy and paste the text currently in the documentation. If you want improve graphs or photos, please provide a screenshot of the original.

**Where is this stated?**
Provide additional information about the location where you have copied the above statement from.

**Why do you want to improve the statement?**
Please explain why the statement needs to be updated. This can be because it is confusing, incorrect, spelling/grammatical errors, etc. 

**Proposed statement**
Please propose how you would rewrite the statement. If you have a precise proposal, please make the changes and open a pull-request.

**Additional info**
Add any useful information here.
