// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: grpc/end.proto

package regression

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EndServiceClient is the client API for EndService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndServiceClient interface {
	End(ctx context.Context, in *Endrequest, opts ...grpc.CallOption) (*Endresponse, error)
}

type endServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndServiceClient(cc grpc.ClientConnInterface) EndServiceClient {
	return &endServiceClient{cc}
}

func (c *endServiceClient) End(ctx context.Context, in *Endrequest, opts ...grpc.CallOption) (*Endresponse, error) {
	out := new(Endresponse)
	err := c.cc.Invoke(ctx, "/end.EndService/End", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndServiceServer is the server API for EndService service.
// All implementations must embed UnimplementedEndServiceServer
// for forward compatibility
type EndServiceServer interface {
	End(context.Context, *Endrequest) (*Endresponse, error)
	mustEmbedUnimplementedEndServiceServer()
}

// UnimplementedEndServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEndServiceServer struct {
}

func (UnimplementedEndServiceServer) End(context.Context, *Endrequest) (*Endresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method End not implemented")
}
func (UnimplementedEndServiceServer) mustEmbedUnimplementedEndServiceServer() {}

// UnsafeEndServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndServiceServer will
// result in compilation errors.
type UnsafeEndServiceServer interface {
	mustEmbedUnimplementedEndServiceServer()
}

func RegisterEndServiceServer(s grpc.ServiceRegistrar, srv EndServiceServer) {
	s.RegisterService(&EndService_ServiceDesc, srv)
}

func _EndService_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Endrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndServiceServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/end.EndService/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndServiceServer).End(ctx, req.(*Endrequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndService_ServiceDesc is the grpc.ServiceDesc for EndService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "end.EndService",
	HandlerType: (*EndServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "End",
			Handler:    _EndService_End_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/end.proto",
}
