package models

import (
	"strings"
	"testing"

	yamlLib "gopkg.in/yaml.v3"
)

// TestPostgresV3Response_Validate_RowsAndCopyOut_Mutex confirms the
// schema-level mutual-exclusion gap between Rows and CopyOut.
//
// Per the PG wire protocol, a single response carries either DataRow
// traffic OR CopyData traffic — never both. The struct doc on
// PostgresV3Response.Rows says so explicitly ("Mutually exclusive
// with CopyOut / CopyIn"), but nothing in the code enforces it: a
// caller can populate both fields, marshal cleanly, unmarshal cleanly,
// and the replay emitter then nondeterministically picks one and
// silently drops the other.
//
// This test pins the invariant. It constructs a malformed response
// with both Rows and CopyOut populated, round-trips through YAML,
// and asserts Validate() rejects it. A failing Validate() before the
// fix landed is the load-bearing signal.
func TestPostgresV3Response_Validate_RowsAndCopyOut_Mutex(t *testing.T) {
	orig := PostgresV3Response{
		CommandComplete: "SELECT 1",
		Rows: []PostgresV3Cells{
			{{Value: int64(1)}},
		},
		CopyOut: &PostgresV3CopyOutPayload{
			OverallFormat:     0,
			ColumnFormatCodes: []uint16{0},
			Data:              [][]byte{{'a', 'b', 'c'}},
		},
	}

	// Step 1: malformed shape must serialize cleanly today — that is
	// the bug. Any error here would mean the YAML layer already
	// rejected it and there's nothing to validate.
	encoded, err := yamlLib.Marshal(&orig)
	if err != nil {
		t.Fatalf("yaml.Marshal of malformed response failed: %v — "+
			"the bug premise (silent serialization) is invalidated", err)
	}

	// Step 2: malformed shape must deserialize cleanly as well. The
	// loader has no custom UnmarshalYAML on PostgresV3Response, so a
	// straight round-trip is expected.
	var decoded PostgresV3Response
	if err := yamlLib.Unmarshal(encoded, &decoded); err != nil {
		t.Fatalf("yaml.Unmarshal of malformed response failed: %v — "+
			"the bug premise (silent deserialization) is invalidated", err)
	}
	if len(decoded.Rows) == 0 {
		t.Fatalf("Rows lost during round-trip — fixture broken")
	}
	if decoded.CopyOut == nil {
		t.Fatalf("CopyOut lost during round-trip — fixture broken")
	}

	// Step 3: Validate() must reject the combination. This is the
	// assertion that fails today (no Validate exists / no rule fires)
	// and passes after the fix.
	err = decoded.Validate()
	if err == nil {
		t.Fatalf("Validate(): want non-nil error on response with both " +
			"Rows and CopyOut populated, got nil — mutual-exclusion " +
			"gap not closed")
	}
	if !strings.Contains(err.Error(), "Rows") || !strings.Contains(err.Error(), "CopyOut") {
		t.Fatalf("Validate() error should mention both Rows and CopyOut, got: %v", err)
	}
}

// TestPostgresV3Response_Validate_RejectsHandWrittenMalformedYAML feeds
// a hand-written YAML fixture (NOT generated by Go marshal, to ensure
// a real loader path is exercised) carrying both `rows:` and
// `copyOut:` keys, unmarshals it into a PostgresV3Response, and
// asserts Validate() rejects it.
//
// This complements the in-memory round-trip test: it pins the bug at
// the on-disk layer where a hand-edited or recorder-bug-produced
// mocks.yaml would actually arrive.
func TestPostgresV3Response_Validate_RejectsHandWrittenMalformedYAML(t *testing.T) {
	// Each Rows entry is a one-cell row; CopyOut has a single
	// three-byte data packet encoded as a sequence of byte values
	// (matching what yaml.v3's default encoder produces for [][]byte).
	// The two top-level keys (rows + copyOut) are the offence
	// Validate() must catch — both populated on the same response.
	const malformed = `
commandComplete: "SELECT 1"
rows:
  - - "1"
copyOut:
  overallFormat: 0
  columnFormatCodes: [0]
  data:
    - [97, 98, 99]
`
	var resp PostgresV3Response
	if err := yamlLib.Unmarshal([]byte(malformed), &resp); err != nil {
		t.Fatalf("yaml.Unmarshal of hand-written malformed fixture failed: %v — "+
			"loader rejected at YAML layer; this test exercises the "+
			"Validate() path which only runs after a clean parse", err)
	}

	// Sanity: both fields populated post-parse, otherwise the test
	// cannot prove the bug.
	if len(resp.Rows) == 0 {
		t.Fatalf("hand-written fixture parsed without Rows — fixture broken")
	}
	if resp.CopyOut == nil {
		t.Fatalf("hand-written fixture parsed without CopyOut — fixture broken")
	}

	if err := resp.Validate(); err == nil {
		t.Fatalf("Validate(): want non-nil error on hand-written " +
			"malformed YAML carrying both rows and copyOut, got nil")
	}
}

// TestPostgresV3Response_Validate_RowsAndCopyIn_Mutex pins the same
// mutual-exclusion rule on the CopyIn axis. The struct doc on Rows
// names CopyIn alongside CopyOut as mutually exclusive, so a
// validator that catches Rows+CopyOut but skips Rows+CopyIn would
// leave half the gap open.
func TestPostgresV3Response_Validate_RowsAndCopyIn_Mutex(t *testing.T) {
	resp := PostgresV3Response{
		CommandComplete: "SELECT 1",
		Rows: []PostgresV3Cells{
			{{Value: int64(1)}},
		},
		CopyIn: &PostgresV3CopyInPayload{
			OverallFormat:     0,
			ColumnFormatCodes: []uint16{0},
		},
	}
	if err := resp.Validate(); err == nil {
		t.Fatalf("Validate(): want non-nil error on response with both " +
			"Rows and CopyIn populated, got nil")
	}
}

// TestPostgresV3Response_Validate_CopyInAndCopyOut_Mutex pins that a
// single response cannot simultaneously carry server-side CopyOut
// and CopyIn payloads. The two are different sub-protocols (TO STDOUT
// vs FROM STDIN) keyed off a single tag byte ('H' vs 'G'); the
// recorder is not supposed to ever populate both, but the struct
// doesn't prevent it.
func TestPostgresV3Response_Validate_CopyInAndCopyOut_Mutex(t *testing.T) {
	resp := PostgresV3Response{
		CommandComplete: "COPY 0",
		CopyOut: &PostgresV3CopyOutPayload{
			OverallFormat:     0,
			ColumnFormatCodes: []uint16{0},
		},
		CopyIn: &PostgresV3CopyInPayload{
			OverallFormat:     0,
			ColumnFormatCodes: []uint16{0},
		},
	}
	if err := resp.Validate(); err == nil {
		t.Fatalf("Validate(): want non-nil error on response with both " +
			"CopyOut and CopyIn populated, got nil")
	}
}

// TestPostgresV3Response_Validate_FunctionCall_Mutex pins the
// FunctionCall axis. The struct doc on FunctionCall states the field
// is "Mutually exclusive with Rows / CopyOut / CopyIn — an invocation
// is either a SQL query or a fastpath function invocation, never
// both." Validate() must enforce that.
func TestPostgresV3Response_Validate_FunctionCall_Mutex(t *testing.T) {
	cases := []struct {
		name string
		resp PostgresV3Response
	}{
		{
			name: "FunctionCall+Rows",
			resp: PostgresV3Response{
				Rows:         []PostgresV3Cells{{{Value: int64(1)}}},
				FunctionCall: &PostgresV3FunctionCall{OID: 950},
			},
		},
		{
			name: "FunctionCall+CopyOut",
			resp: PostgresV3Response{
				CopyOut:      &PostgresV3CopyOutPayload{OverallFormat: 0},
				FunctionCall: &PostgresV3FunctionCall{OID: 950},
			},
		},
		{
			name: "FunctionCall+CopyIn",
			resp: PostgresV3Response{
				CopyIn:       &PostgresV3CopyInPayload{OverallFormat: 0},
				FunctionCall: &PostgresV3FunctionCall{OID: 950},
			},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := tc.resp.Validate(); err == nil {
				t.Fatalf("Validate(): want non-nil error on %s, got nil", tc.name)
			}
		})
	}
}

// TestPostgresV3Response_Validate_DispatcherLoadPath simulates the
// dispatcher load path: a Mock carrying a malformed PostgresV3Response
// arrives at the loader; the loader must reject it before it reaches
// the wire emitter.
//
// We model the dispatcher's per-mock sweep with a tiny helper that
// runs Validate() on each query response, mirroring what
// integrations/pkg/postgres/v3/types/index_loader.go::convertQuery
// would do once Validate() is wired in there.
func TestPostgresV3Response_Validate_DispatcherLoadPath(t *testing.T) {
	mocks := []*Mock{
		{
			Name: "good-mock",
			Kind: PostgresV3,
			Spec: MockSpec{
				PostgresV3: &PostgresV3Spec{
					Type: PostgresV3TypeQuery,
					Query: &PostgresV3QuerySpec{
						SQLAstHash: "sha256:deadbeef",
						Response: &PostgresV3Response{
							CommandComplete: "SELECT 1",
							Rows:            []PostgresV3Cells{{{Value: int64(1)}}},
						},
					},
				},
			},
		},
		{
			Name: "malformed-mock",
			Kind: PostgresV3,
			Spec: MockSpec{
				PostgresV3: &PostgresV3Spec{
					Type: PostgresV3TypeQuery,
					Query: &PostgresV3QuerySpec{
						SQLAstHash: "sha256:cafebabe",
						Response: &PostgresV3Response{
							CommandComplete: "SELECT 1",
							Rows: []PostgresV3Cells{
								{{Value: int64(1)}},
							},
							CopyOut: &PostgresV3CopyOutPayload{
								OverallFormat: 0,
								Data:          [][]byte{{'a'}},
							},
						},
					},
				},
			},
		},
	}

	// Mimic a dispatcher sweep that calls Validate() per mock. The
	// real wiring lives in the integrations repo's BuildIndex /
	// convertQueryResponse path; this test pins the contract that
	// SHOULD fire there once Validate() is plumbed through.
	rejected := make([]string, 0, len(mocks))
	for _, m := range mocks {
		if m == nil || m.Spec.PostgresV3 == nil {
			continue
		}
		if m.Spec.PostgresV3.Query == nil || m.Spec.PostgresV3.Query.Response == nil {
			continue
		}
		if err := m.Spec.PostgresV3.Query.Response.Validate(); err != nil {
			rejected = append(rejected, m.Name)
		}
	}

	if len(rejected) != 1 {
		t.Fatalf("dispatcher sweep: want exactly 1 rejection, got %d (%v)",
			len(rejected), rejected)
	}
	if rejected[0] != "malformed-mock" {
		t.Fatalf("dispatcher sweep: rejected %q, expected %q",
			rejected[0], "malformed-mock")
	}
}

// TestPostgresV3Response_Validate_ValidShapesPass ensures Validate()
// does not produce false positives: any single-axis response — Rows
// only, CopyOut only, CopyIn only, FunctionCall only, Error only,
// or fully empty (just notices/notifications) — must pass.
func TestPostgresV3Response_Validate_ValidShapesPass(t *testing.T) {
	cases := []struct {
		name string
		resp PostgresV3Response
	}{
		{
			name: "rows-only",
			resp: PostgresV3Response{
				CommandComplete: "SELECT 1",
				Rows:            []PostgresV3Cells{{{Value: int64(1)}}},
			},
		},
		{
			name: "copyOut-only",
			resp: PostgresV3Response{
				CommandComplete: "COPY 0",
				CopyOut:         &PostgresV3CopyOutPayload{OverallFormat: 0},
			},
		},
		{
			name: "copyIn-only",
			resp: PostgresV3Response{
				CommandComplete: "COPY 0",
				CopyIn:          &PostgresV3CopyInPayload{OverallFormat: 0},
			},
		},
		{
			name: "functionCall-only",
			resp: PostgresV3Response{
				FunctionCall: &PostgresV3FunctionCall{OID: 950},
			},
		},
		{
			name: "empty-response",
			resp: PostgresV3Response{
				CommandComplete: "BEGIN",
			},
		},
		{
			name: "error-with-rows",
			// An ErrorResponse can legitimately ride alongside any
			// partial Rows the server emitted before the error; the
			// rule is row-vs-copy mutual exclusion, not row-vs-error.
			resp: PostgresV3Response{
				Rows:  []PostgresV3Cells{{{Value: int64(1)}}},
				Error: &PostgresV3Error{Code: "42P01", Message: "relation does not exist"},
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := tc.resp.Validate(); err != nil {
				t.Fatalf("Validate() returned %v on valid %s response", err, tc.name)
			}
		})
	}
}
