package yaml

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"testing"

	"go.uber.org/zap"
)

// getTestLogger creates a test logger
func getTestLogger() *zap.Logger {
	logger, _ := zap.NewDevelopment()
	return logger
}

// TestMockReaderWindowsLineEndings tests that the reader correctly handles
// Windows-style CRLF (\r\n) line endings
func TestMockReaderWindowsLineEndings(t *testing.T) {
	ctx := context.Background()
	logger := getTestLogger()

	// Create a temporary directory
	tempDir, err := os.MkdirTemp("", "mockreader_windows_test")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	// Create mock content with Windows-style CRLF line endings
	// Using explicit \r\n to simulate Windows line endings
	windowsMockContent := "# Generated by Keploy\r\n" +
		"---\r\n" +
		"version: api.keploy.io/v1beta1\r\n" +
		"kind: Http\r\n" +
		"name: mock-1\r\n" +
		"spec:\r\n" +
		"    metadata:\r\n" +
		"        type: config\r\n" +
		"    requests:\r\n" +
		"        - header:\r\n" +
		"            length: 100\r\n" +
		"    created: 1767366025\r\n" +
		"---\r\n" +
		"version: api.keploy.io/v1beta1\r\n" +
		"kind: Http\r\n" +
		"name: mock-2\r\n" +
		"spec:\r\n" +
		"    metadata:\r\n" +
		"        type: config\r\n" +
		"    requests:\r\n" +
		"        - header:\r\n" +
		"            length: 200\r\n" +
		"    created: 1767366026\r\n" +
		"---\r\n" +
		"version: api.keploy.io/v1beta1\r\n" +
		"kind: Http\r\n" +
		"name: mock-3\r\n" +
		"spec:\r\n" +
		"    metadata:\r\n" +
		"        type: config\r\n" +
		"    requests:\r\n" +
		"        - header:\r\n" +
		"            length: 300\r\n" +
		"    created: 1767366027\r\n"

	// Write the mock file with Windows line endings
	mockFilePath := filepath.Join(tempDir, "mocks.yaml")
	err = os.WriteFile(mockFilePath, []byte(windowsMockContent), 0644)
	if err != nil {
		t.Fatalf("Failed to write mock file: %v", err)
	}

	// Verify the file was written with CRLF
	fileContent, err := os.ReadFile(mockFilePath)
	if err != nil {
		t.Fatalf("Failed to read mock file: %v", err)
	}
	crlfCount := 0
	for i := 0; i < len(fileContent)-1; i++ {
		if fileContent[i] == '\r' && fileContent[i+1] == '\n' {
			crlfCount++
		}
	}
	t.Logf("File contains %d CRLF sequences", crlfCount)

	// Create the reader and read mocks
	reader, err := NewMockReader(ctx, logger, tempDir, "mocks")
	if err != nil {
		t.Fatalf("Failed to create MockReader: %v", err)
	}
	defer reader.Close()

	expectedNames := []string{"mock-1", "mock-2", "mock-3"}
	mockCount := 0

	for {
		doc, err := reader.ReadNextDoc()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("Failed to read mock %d: %v", mockCount, err)
		}

		// Validate document
		if mockCount < len(expectedNames) {
			if doc.Name != expectedNames[mockCount] {
				t.Errorf("Mock %d name mismatch: got %q, want %q", mockCount, doc.Name, expectedNames[mockCount])
			}
		}

		t.Logf("Successfully read mock: %s (kind: %s)", doc.Name, doc.Kind)
		mockCount++
	}

	if mockCount != 3 {
		t.Errorf("Mock count mismatch: got %d, want 3", mockCount)
	}

	t.Logf("Successfully read %d mocks with Windows CRLF line endings", mockCount)
}

// TestMockReaderMixedLineEndings tests handling of files with mixed line endings
// (which can happen when files are edited on different platforms)
func TestMockReaderMixedLineEndings(t *testing.T) {
	ctx := context.Background()
	logger := getTestLogger()

	// Create a temporary directory
	tempDir, err := os.MkdirTemp("", "mockreader_mixed_test")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tempDir)

	// Create mock content with mixed line endings (some LF, some CRLF)
	mixedMockContent := "# Generated by Keploy\n" + // Unix LF
		"---\r\n" + // Windows CRLF
		"version: api.keploy.io/v1beta1\n" + // Unix LF
		"kind: Http\r\n" + // Windows CRLF
		"name: mock-mixed-1\n" + // Unix LF
		"spec:\r\n" + // Windows CRLF
		"    metadata:\n" + // Unix LF
		"        type: config\n" +
		"    created: 1767366025\n" +
		"---\n" + // Unix LF separator
		"version: api.keploy.io/v1beta1\r\n" + // Windows CRLF
		"kind: Http\n" + // Unix LF
		"name: mock-mixed-2\r\n" + // Windows CRLF
		"spec:\n" +
		"    metadata:\r\n" +
		"        type: config\n" +
		"    created: 1767366026\n"

	// Write the mock file
	mockFilePath := filepath.Join(tempDir, "mocks.yaml")
	err = os.WriteFile(mockFilePath, []byte(mixedMockContent), 0644)
	if err != nil {
		t.Fatalf("Failed to write mock file: %v", err)
	}

	// Create the reader and read mocks
	reader, err := NewMockReader(ctx, logger, tempDir, "mocks")
	if err != nil {
		t.Fatalf("Failed to create MockReader: %v", err)
	}
	defer reader.Close()

	expectedNames := []string{"mock-mixed-1", "mock-mixed-2"}
	mockCount := 0

	for {
		doc, err := reader.ReadNextDoc()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("Failed to read mock %d: %v", mockCount, err)
		}

		// Validate document
		if mockCount < len(expectedNames) {
			if doc.Name != expectedNames[mockCount] {
				t.Errorf("Mock %d name mismatch: got %q, want %q", mockCount, doc.Name, expectedNames[mockCount])
			}
		}

		t.Logf("Successfully read mock: %s (kind: %s)", doc.Name, doc.Kind)
		mockCount++
	}

	if mockCount != 2 {
		t.Errorf("Mock count mismatch: got %d, want 2", mockCount)
	}

	t.Logf("Successfully read %d mocks with mixed line endings", mockCount)
}

// A file that does not end with a newline still ends its last document with
// its last line, whether that document has one line or several; a final
// "---" without a newline is a separator, not a document.
func TestMockReaderKeepsTheLastLineOfAFileWithoutAFinalNewline(t *testing.T) {
	for _, tc := range []struct {
		name, content string
		want          []string
		// unterminated is what Unterminated says after each document.
		unterminated []bool
	}{
		{
			name:         "several lines",
			content:      "# Generated by Keploy\n---\nkind: Http\nname: mock-1\n---\nkind: Http\nname: mock-2\nspec:\n    created: 2",
			want:         []string{"kind: Http\nname: mock-1\n", "kind: Http\nname: mock-2\nspec:\n    created: 2"},
			unterminated: []bool{false, true},
		},
		{
			name:         "one line",
			content:      "---\nkind: Http\nname: mock-1\n---\nname: mock-2",
			want:         []string{"kind: Http\nname: mock-1\n", "name: mock-2"},
			unterminated: []bool{false, true},
		},
		{
			name:         "a final separator",
			content:      "---\nkind: Http\nname: mock-1\n---",
			want:         []string{"kind: Http\nname: mock-1\n"},
			unterminated: []bool{false},
		},
		{
			name:         "a final newline, as keploy writes",
			content:      "---\nkind: Http\nname: mock-1\n---\nkind: Http\nname: mock-2\n",
			want:         []string{"kind: Http\nname: mock-1\n", "kind: Http\nname: mock-2\n"},
			unterminated: []bool{false, false},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.WriteFile(filepath.Join(dir, "mocks.yaml"), []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			reader, err := NewMockReader(context.Background(), zap.NewNop(), dir, "mocks")
			if err != nil {
				t.Fatal(err)
			}
			defer reader.Close()
			var got []string
			for {
				doc, data, err := reader.ReadNextDocBytes()
				if err == io.EOF {
					break
				}
				if err != nil {
					t.Fatal(err)
				}
				if want := "mock-" + string(rune('1'+len(got))); doc.Name != want {
					t.Fatalf("document %d is %q, want %q", len(got), doc.Name, want)
				}
				if u := reader.Unterminated(); u != tc.unterminated[len(got)] {
					t.Fatalf("document %d: Unterminated = %v, want %v", len(got), u, tc.unterminated[len(got)])
				}
				got = append(got, string(data))
			}
			if len(got) != len(tc.want) {
				t.Fatalf("read %d documents %q, want %q", len(got), got, tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Fatalf("document %d is %q, want %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

// A file cut part-way through its last line, as an interrupted write leaves
// it: the reader says the last document is unterminated, and hands it back as
// read even though it does not parse, so the caller can judge it (and a
// rewrite can copy it). A document that does not parse elsewhere in the file
// is handed back too, and is not unterminated.
func TestMockReaderHandsBackAnUnparsableLastDocument(t *testing.T) {
	for _, tc := range []struct {
		name, ext, content, last string
		format                   Format
		unterminated             bool
	}{
		{"yaml, cut inside a key", "yaml", "---\nkind: Http\nname: mock-1\n---\nkind: Http\nname: mock-2\nspe", "kind: Http\nname: mock-2\nspe", FormatYAML, true},
		{"json, cut inside a value", "json", "{\"kind\":\"Http\",\"name\":\"mock-1\"}\n{\"kind\":\"Http\",\"name\":\"mo", "{\"kind\":\"Http\",\"name\":\"mo", FormatJSON, true},
		{"json, a bad line that ends", "json", "{\"kind\":\"Http\",\"name\":\"mock-1\"}\n{\"kind\":\"Http\",\"name\":\"mo\n", "{\"kind\":\"Http\",\"name\":\"mo", FormatJSON, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.WriteFile(filepath.Join(dir, "mocks."+tc.ext), []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			reader, err := NewMockReaderF(context.Background(), zap.NewNop(), dir, "mocks", tc.format)
			if err != nil {
				t.Fatal(err)
			}
			defer reader.Close()
			next := func() ([]byte, error) {
				if tc.format == FormatJSON {
					_, data, err := reader.ReadNextDocJSONBytes()
					return data, err
				}
				_, data, err := reader.ReadNextDocBytes()
				return data, err
			}
			if _, err := next(); err != nil {
				t.Fatalf("the first document: %v", err)
			}
			data, err := next()
			if err == nil || string(data) != tc.last || reader.Unterminated() != tc.unterminated {
				t.Fatalf("got %q, %v, unterminated %v; want %q, a parse error, unterminated %v", data, err, reader.Unterminated(), tc.last, tc.unterminated)
			}
		})
	}
}
