package yaml

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"go.uber.org/zap"
)

// mockTemplate is a sample mock document template that resembles real Keploy mocks
const mockTemplate = `version: api.keploy.io/v1beta1
kind: Mongo
name: mock-%d
spec:
    metadata:
        connID: "%d"
        operation: '{ OpQuery flags: [SecondaryOK], fullCollectionName: admin.$cmd, numberToSkip: 0, numberToReturn: -1, query: {"isMaster": {"$numberInt":"1"},"helloOk": true,"compression": [],"client": {"driver": {"name": "mongo-go-driver","version": "1.17.6"},"os": {"type": "linux","architecture": "amd64"},"platform": "go1.24.11","env": {"container": {"runtime": "docker"}}}}, returnFieldsSelector:  }'
        type: config
    requests:
        - header:
            length: 277
            requestId: %d
            responseTo: 0
            Opcode: 2004
          message:
            flags: 4
            collection_name: admin.$cmd
            number_to_skip: 0
            number_to_return: -1
            query: '{"isMaster":{"$numberInt":"1"},"helloOk":true,"compression":[],"client":{"driver":{"name":"mongo-go-driver","version":"1.17.6"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.24.11","env":{"container":{"runtime":"docker"}}}}'
            return_fields_selector: ""
    responses:
        - header:
            length: 1118
            requestId: 9264450
            responseTo: %d
            Opcode: 1
          message:
            response_flags: 8
            cursor_id: 0
            starting_from: 0
            number_returned: 1
            documents:
                - '{"helloOk":true,"topologyVersion":{"processId":{"$oid":"6951a84bb7b1880dca5bb311"},"counter":{"$numberLong":"3"}},"hosts":["ac-zne2r2v-shard-00-00.p1xxqop.mongodb.net:27017","ac-zne2r2v-shard-00-01.p1xxqop.mongodb.net:27017","ac-zne2r2v-shard-00-02.p1xxqop.mongodb.net:27017"],"setName":"atlas-1v3sai-shard-0","setVersion":{"$numberInt":"23"},"ismaster":false,"secondary":true,"primary":"ac-zne2r2v-shard-00-02.p1xxqop.mongodb.net:27017","tags":{"diskState":"READY","nodeType":"ELECTABLE","availabilityZone":"usw2-az2","provider":"AWS","workloadType":"OPERATIONAL","region":"US_WEST_2"},"me":"ac-zne2r2v-shard-00-01.p1xxqop.mongodb.net:27017","lastWrite":{"opTime":{"ts":{"$timestamp":{"t":1767366014,"i":1}},"t":{"$numberLong":"81"}},"lastWriteDate":{"$date":{"$numberLong":"1767366014000"}},"majorityOpTime":{"ts":{"$timestamp":{"t":1767366014,"i":1}},"t":{"$numberLong":"81"}},"majorityWriteDate":{"$date":{"$numberLong":"1767366014000"}}},"maxBsonObjectSize":{"$numberInt":"16777216"},"maxMessageSizeBytes":{"$numberInt":"48000000"},"maxWriteBatchSize":{"$numberInt":"100000"},"localTime":{"$date":{"$numberLong":"1767366025641"}},"logicalSessionTimeoutMinutes":{"$numberInt":"30"},"connectionId":{"$numberInt":"28566"},"minWireVersion":{"$numberInt":"0"},"maxWireVersion":{"$numberInt":"25"},"readOnly":false,"ok":{"$numberDouble":"1.0"},"$clusterTime":{"clusterTime":{"$timestamp":{"t":1767366014,"i":1}},"signature":{"hash":{"$binary":{"base64":"dOE3E/Tgl8MKFwqo+2n8SsuynRo=","subType":"00"}},"keyId":{"$numberLong":"7553942889126952962"}}},"operationTime":{"$timestamp":{"t":1767366014,"i":1}}}'
          read_delay: 290441750
    created: 1767366025
    reqTimestampMock: 2026-01-02T15:00:25.542221401Z
    resTimestampMock: 2026-01-02T15:00:25.542221481Z
`

// getLogger creates a test logger
func getTestLogger() *zap.Logger {
	logger, _ := zap.NewDevelopment()
	return logger
}

// generateLargeMockFile creates a mock file of approximately the specified size in GB
func generateLargeMockFile(t *testing.T, dir string, sizeGB float64) (string, int) {
	t.Helper()

	filePath := filepath.Join(dir, "mocks.yaml")
	file, err := os.Create(filePath)
	if err != nil {
		t.Fatalf("Failed to create mock file: %v", err)
	}
	defer file.Close()

	// Write header comment
	_, err = file.WriteString("# Generated by Keploy (test)\n")
	if err != nil {
		t.Fatalf("Failed to write header: %v", err)
	}

	targetSize := int64(sizeGB * 1024 * 1024 * 1024) // Convert GB to bytes
	var currentSize int64
	mockCount := 0

	// Calculate approximate size of one mock document
	sampleMock := fmt.Sprintf(mockTemplate, 0, 0, 0, 0)
	mockSize := len(sampleMock) + 4 // +4 for "---\n"

	t.Logf("Target file size: %.2f GB (%d bytes)", sizeGB, targetSize)
	t.Logf("Each mock is approximately %d bytes", mockSize)
	t.Logf("Estimated mocks needed: %d", targetSize/int64(mockSize))

	startTime := time.Now()
	lastLogTime := startTime

	for currentSize < targetSize {
		// Write document separator (except for first document)
		if mockCount > 0 {
			_, err = file.WriteString("---\n")
			if err != nil {
				t.Fatalf("Failed to write separator: %v", err)
			}
			currentSize += 4
		}

		// Write mock document
		mockDoc := fmt.Sprintf(mockTemplate, mockCount, mockCount%100, mockCount*2+1, mockCount*2+1)
		n, err := file.WriteString(mockDoc)
		if err != nil {
			t.Fatalf("Failed to write mock %d: %v", mockCount, err)
		}
		currentSize += int64(n)
		mockCount++

		// Log progress every 10 seconds
		if time.Since(lastLogTime) > 10*time.Second {
			progress := float64(currentSize) / float64(targetSize) * 100
			t.Logf("Progress: %.1f%% (%d mocks, %.2f GB written)", progress, mockCount, float64(currentSize)/(1024*1024*1024))
			lastLogTime = time.Now()
		}
	}

	// Sync to disk
	err = file.Sync()
	if err != nil {
		t.Fatalf("Failed to sync file: %v", err)
	}

	elapsed := time.Since(startTime)
	actualSize := currentSize
	t.Logf("File generation completed in %v", elapsed)
	t.Logf("Final file size: %.2f GB (%d bytes)", float64(actualSize)/(1024*1024*1024), actualSize)
	t.Logf("Total mocks written: %d", mockCount)

	return filePath, mockCount
}

func testLineBasedMockReader(t *testing.T, ctx context.Context, logger *zap.Logger, tempDir string, expectedMocks int) {
	runtime.GC()
	var memBefore runtime.MemStats
	runtime.ReadMemStats(&memBefore)

	startTime := time.Now()

	reader, err := NewLineBasedMockReader(ctx, logger, tempDir, "mocks")
	if err != nil {
		t.Fatalf("Failed to create LineBasedMockReader: %v", err)
	}
	defer reader.Close()

	mockCount := 0
	lastLogTime := startTime

	for {
		doc, err := reader.ReadNextDoc()
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("Failed to read mock %d: %v", mockCount, err)
		}

		mockCount++

		// Validate document
		if doc.Name == "" {
			t.Errorf("Mock %d has empty name", mockCount)
		}

		// Log progress every 30 seconds
		if time.Since(lastLogTime) > 30*time.Second {
			var memCurrent runtime.MemStats
			runtime.ReadMemStats(&memCurrent)
			t.Logf("Progress: %d mocks read, Memory: %.2f MB allocated",
				mockCount, float64(memCurrent.Alloc)/(1024*1024))
			lastLogTime = time.Now()
		}
	}

	elapsed := time.Since(startTime)

	var memAfter runtime.MemStats
	runtime.ReadMemStats(&memAfter)

	t.Logf("LineBasedMockReader completed in %v", elapsed)
	t.Logf("Mocks read: %d (expected: %d)", mockCount, expectedMocks)
	t.Logf("Memory: Before=%.2f MB, After=%.2f MB, Delta=%.2f MB",
		float64(memBefore.Alloc)/(1024*1024),
		float64(memAfter.Alloc)/(1024*1024),
		float64(memAfter.Alloc-memBefore.Alloc)/(1024*1024))

	if mockCount != expectedMocks {
		t.Errorf("Mock count mismatch: got %d, want %d", mockCount, expectedMocks)
	}
}
