// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: grpc/regression/services.proto

package regression

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcServiceClient is the client API for GrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcServiceClient interface {
	End(ctx context.Context, in *EndRequest, opts ...grpc.CallOption) (*EndResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	GetTC(ctx context.Context, in *GetTCRequest, opts ...grpc.CallOption) (*TestCase, error)
	GetTCS(ctx context.Context, in *GetTCSRequest, opts ...grpc.CallOption) (*GetTCSResponse, error)
	PostTC(ctx context.Context, in *TestCaseReq, opts ...grpc.CallOption) (*PostTCResponse, error)
	DeNoise(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*DeNoiseResponse, error)
	Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResponse, error)
}

type grpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcServiceClient(cc grpc.ClientConnInterface) GrpcServiceClient {
	return &grpcServiceClient{cc}
}

func (c *grpcServiceClient) End(ctx context.Context, in *EndRequest, opts ...grpc.CallOption) (*EndResponse, error) {
	out := new(EndResponse)
	err := c.cc.Invoke(ctx, "/services.GrpcService/End", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/services.GrpcService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) GetTC(ctx context.Context, in *GetTCRequest, opts ...grpc.CallOption) (*TestCase, error) {
	out := new(TestCase)
	err := c.cc.Invoke(ctx, "/services.GrpcService/GetTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) GetTCS(ctx context.Context, in *GetTCSRequest, opts ...grpc.CallOption) (*GetTCSResponse, error) {
	out := new(GetTCSResponse)
	err := c.cc.Invoke(ctx, "/services.GrpcService/GetTCS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) PostTC(ctx context.Context, in *TestCaseReq, opts ...grpc.CallOption) (*PostTCResponse, error) {
	out := new(PostTCResponse)
	err := c.cc.Invoke(ctx, "/services.GrpcService/PostTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) DeNoise(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*DeNoiseResponse, error) {
	out := new(DeNoiseResponse)
	err := c.cc.Invoke(ctx, "/services.GrpcService/DeNoise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcServiceClient) Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/services.GrpcService/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServiceServer is the server API for GrpcService service.
// All implementations must embed UnimplementedGrpcServiceServer
// for forward compatibility
type GrpcServiceServer interface {
	End(context.Context, *EndRequest) (*EndResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	GetTC(context.Context, *GetTCRequest) (*TestCase, error)
	GetTCS(context.Context, *GetTCSRequest) (*GetTCSResponse, error)
	PostTC(context.Context, *TestCaseReq) (*PostTCResponse, error)
	DeNoise(context.Context, *TestReq) (*DeNoiseResponse, error)
	Test(context.Context, *TestReq) (*TestResponse, error)
	mustEmbedUnimplementedGrpcServiceServer()
}

// UnimplementedGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcServiceServer struct {
}

func (UnimplementedGrpcServiceServer) End(context.Context, *EndRequest) (*EndResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method End not implemented")
}
func (UnimplementedGrpcServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedGrpcServiceServer) GetTC(context.Context, *GetTCRequest) (*TestCase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTC not implemented")
}
func (UnimplementedGrpcServiceServer) GetTCS(context.Context, *GetTCSRequest) (*GetTCSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTCS not implemented")
}
func (UnimplementedGrpcServiceServer) PostTC(context.Context, *TestCaseReq) (*PostTCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTC not implemented")
}
func (UnimplementedGrpcServiceServer) DeNoise(context.Context, *TestReq) (*DeNoiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeNoise not implemented")
}
func (UnimplementedGrpcServiceServer) Test(context.Context, *TestReq) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGrpcServiceServer) mustEmbedUnimplementedGrpcServiceServer() {}

// UnsafeGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServiceServer will
// result in compilation errors.
type UnsafeGrpcServiceServer interface {
	mustEmbedUnimplementedGrpcServiceServer()
}

func RegisterGrpcServiceServer(s grpc.ServiceRegistrar, srv GrpcServiceServer) {
	s.RegisterService(&GrpcService_ServiceDesc, srv)
}

func _GrpcService_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).End(ctx, req.(*EndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_GetTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).GetTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/GetTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).GetTC(ctx, req.(*GetTCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_GetTCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).GetTCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/GetTCS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).GetTCS(ctx, req.(*GetTCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_PostTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestCaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).PostTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/PostTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).PostTC(ctx, req.(*TestCaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_DeNoise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).DeNoise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/DeNoise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).DeNoise(ctx, req.(*TestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.GrpcService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServiceServer).Test(ctx, req.(*TestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcService_ServiceDesc is the grpc.ServiceDesc for GrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.GrpcService",
	HandlerType: (*GrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "End",
			Handler:    _GrpcService_End_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _GrpcService_Start_Handler,
		},
		{
			MethodName: "GetTC",
			Handler:    _GrpcService_GetTC_Handler,
		},
		{
			MethodName: "GetTCS",
			Handler:    _GrpcService_GetTCS_Handler,
		},
		{
			MethodName: "PostTC",
			Handler:    _GrpcService_PostTC_Handler,
		},
		{
			MethodName: "DeNoise",
			Handler:    _GrpcService_DeNoise_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _GrpcService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/regression/services.proto",
}
