package mockdb

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"go.keploy.io/server/v3/pkg/models"
	"go.keploy.io/server/v3/pkg/platform/yaml"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"go.uber.org/zap/zaptest/observer"
	yamlLib "gopkg.in/yaml.v3"
)

// Documents this keploy cannot decode: a kind with a hyphen (enterprise-only,
// skipped at Debug), a kind it has never heard of (written by a newer keploy,
// skipped with an ERROR), and a connection failure with an outcome it does not
// support (likewise). The odd spacing, the key order and the YAML comment are
// there so that a rewrite which re-encoded the document instead of copying it
// would be caught: only a byte-for-byte copy keeps them.
var (
	undecodableYAMLConnFailure = cfDocYAML("cf-newer", "request", "reset", true)
	undecodableJSONConnFailure = cfDocJSON("cf-newer", "request", "reset", true)
)

const (
	undecodableYAMLEnterprise = "version: api.keploy.io/v1beta1\nkind: Acme-Queue\nname: mock-acme\nspec:\n    metadata:\n        type:   mocks   # spacing and this comment survive only a verbatim copy\n    reqTimestampMock: 2026-01-02T03:04:05Z\n"
	undecodableYAMLFuture     = "kind: FutureKind\nversion: api.keploy.io/v1beta1\nname: mock-future\nspec: {address: \"10.0.0.9:443\", answer: [1, 2]}\n"
	undecodableJSONEnterprise = `{"kind":"Acme-Queue", "version":"api.keploy.io/v1beta1","name":"mock-acme","spec":{"metadata":{"type":"mocks"}}}`
	undecodableJSONFuture     = `{"version":"api.keploy.io/v1beta1","kind":"FutureKind","name":"mock-future","spec":{"answer":[1,2],  "address":"10.0.0.9:443"}}`
)

// rewriteFixture records the mixed prune fixture with the two undecodable
// documents in the middle of it, and returns the mock file's path.
func rewriteFixture(t *testing.T, dir, format string) string {
	t.Helper()
	return writePruneFixture(t, dir, format, pruneMixedFixture(), undecodableRaw(format))
}

// undecodableRaw is every undecodable document of the format, as appended to
// a mock file.
func undecodableRaw(format string) string {
	if format == "json" {
		return undecodableJSONEnterprise + "\n" + undecodableJSONFuture + "\n" + undecodableJSONConnFailure + "\n"
	}
	return "---\n" + undecodableYAMLEnterprise + "---\n" + undecodableYAMLFuture + "---\n" + undecodableYAMLConnFailure
}

// assertKeptVerbatim fails unless every undecodable document of the format is
// still in the file at path, byte for byte, as a document of its own.
func assertKeptVerbatim(t *testing.T, path, format string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read the rewritten mock file: %v", err)
	}
	got := string(data)
	if format == "json" {
		lines := map[string]int{}
		for _, l := range strings.Split(got, "\n") {
			lines[l]++
		}
		for _, want := range []string{undecodableJSONEnterprise, undecodableJSONFuture, undecodableJSONConnFailure} {
			if lines[want] != 1 {
				t.Fatalf("the rewrite did not keep a document it cannot decode as the same line, exactly once (found %d).\nwant line: %s\nfile:\n%s", lines[want], want, got)
			}
		}
		return
	}
	docs := map[string]int{}
	for _, d := range yamlDocuments(got) {
		docs[d]++
	}
	for _, want := range []string{undecodableYAMLEnterprise, undecodableYAMLFuture, undecodableYAMLConnFailure} {
		if docs[want] != 1 {
			t.Fatalf("the rewrite did not keep a document it cannot decode, byte for byte, as a document of its own exactly once (found %d).\nwant document:\n%s\nfile:\n%s", docs[want], want, got)
		}
	}
}

// yamlDocuments splits a mocks.yaml the way keploy's reader does: documents
// are separated by "---" lines, and comment lines before the first document's
// content (the "# Generated by Keploy" header) belong to no document.
func yamlDocuments(s string) []string {
	var docs []string
	var cur strings.Builder
	first := true
	for _, line := range strings.SplitAfter(s, "\n") {
		if line == "" {
			continue
		}
		if strings.TrimSpace(line) == "---" {
			if cur.Len() > 0 {
				docs = append(docs, cur.String())
				cur.Reset()
			}
			first = false
			continue
		}
		if first && cur.Len() == 0 && strings.HasPrefix(line, "#") {
			continue
		}
		cur.WriteString(line)
	}
	if cur.Len() > 0 {
		docs = append(docs, cur.String())
	}
	return docs
}

// decodableNames lists the mocks this keploy reads back from the file, which
// must still parse whole after the rewrite.
func decodableNames(t *testing.T, dir, format string) []string {
	t.Helper()
	f := yaml.FormatYAML
	if format == "json" {
		f = yaml.FormatJSON
	}
	ys := NewWithFormat(zap.NewNop(), dir, "mocks", f)
	set, err := ys.GetTestSetMocks(context.Background(), pruneSet, models.BaseTime, time.Now(), nil, nil)
	if err != nil {
		t.Fatalf("read the rewritten file back: %v", err)
	}
	var names []string
	for _, m := range append(set.AllPerTest, set.AllSession...) {
		names = append(names, m.Name)
	}
	return names
}

// A prune drops the mocks no test consumed and rewrites the rest. A document
// it cannot decode is not one it can judge, so it must be copied through
// untouched: dropping it deletes, from the user's recording, mocks that a
// newer keploy (or keploy enterprise) wrote and would have replayed.
func TestUpdateMocks_KeepsADocumentItCannotDecodeVerbatim(t *testing.T) {
	consumed, pruneBefore, startupCutoff := pruneMixedArgs()
	for _, format := range []string{"yaml", "json"} {
		t.Run(format, func(t *testing.T) {
			dir := t.TempDir()
			path := rewriteFixture(t, dir, format)
			before := len(decodableNames(t, dir, format))

			f := yaml.FormatYAML
			if format == "json" {
				f = yaml.FormatJSON
			}
			ys := NewWithFormat(zap.NewNop(), dir, "mocks", f)
			if err := ys.UpdateMocks(context.Background(), pruneSet, consumed, pruneBefore, startupCutoff); err != nil {
				t.Fatalf("UpdateMocks: %v", err)
			}

			assertKeptVerbatim(t, path, format)
			if after := len(decodableNames(t, dir, format)); after == 0 || after >= before {
				t.Fatalf("the prune must still prune the mocks it can judge: %d decodable mocks before, %d after", before, after)
			}
		})
	}
}

// Even a prune that keeps none of the mocks it can judge keeps the documents
// it cannot, so it must not remove the file.
func TestUpdateMocks_KeepsADocumentItCannotDecodeWhenEveryOtherMockGoes(t *testing.T) {
	for _, format := range []string{"yaml", "json"} {
		t.Run(format, func(t *testing.T) {
			dir := t.TempDir()
			raw := undecodableRaw(format)
			// No config mock in this set, nothing consumed, the replay started
			// after every mock and no startup cutoff: the prune keeps none of
			// the mocks it can judge.
			path := writePruneFixture(t, dir, format, []*models.Mock{pruneMySQLMock(1, 2), pruneHTTPMock(2), pruneMongoMock(3), pruneHTTPMock(4)}, raw)
			f := yaml.FormatYAML
			if format == "json" {
				f = yaml.FormatJSON
			}
			ys := NewWithFormat(zap.NewNop(), dir, "mocks", f)
			if err := ys.UpdateMocks(context.Background(), pruneSet, nil, pruneT0.Add(time.Hour), time.Time{}); err != nil {
				t.Fatalf("UpdateMocks: %v", err)
			}
			assertKeptVerbatim(t, path, format)
			if n := len(decodableNames(t, dir, format)); n != 0 {
				t.Fatalf("precondition: the prune should have kept none of the mocks it can judge, kept %d", n)
			}
		})
	}
}

// The noise write-back rewrites the whole file to fold learned request-body
// noise into one mock. Every other document, decodable or not, must come
// through.
func TestPersistMockNoise_KeepsADocumentItCannotDecodeVerbatim(t *testing.T) {
	for _, format := range []string{"yaml", "json"} {
		t.Run(format, func(t *testing.T) {
			dir := t.TempDir()
			path := rewriteFixture(t, dir, format)
			before := len(decodableNames(t, dir, format))

			f := yaml.FormatYAML
			if format == "json" {
				f = yaml.FormatJSON
			}
			ys := NewWithFormat(zap.NewNop(), dir, "mocks", f)
			states := map[string]models.MockState{
				"mock-1": {Name: "mock-1", ReqBodyNoise: map[string][]string{"body.request_id": {}}},
			}
			if err := ys.PersistMockNoise(context.Background(), pruneSet, states); err != nil {
				t.Fatalf("PersistMockNoise: %v", err)
			}

			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(string(data), "body.request_id") {
				t.Fatalf("precondition: the write-back did not rewrite the file; file:\n%s", data)
			}
			assertKeptVerbatim(t, path, format)
			if after := len(decodableNames(t, dir, format)); after != before {
				t.Fatalf("the noise write-back must keep every mock: %d before, %d after", before, after)
			}
			if names := dirEntries(t, filepath.Dir(path)); len(names) != 1 {
				t.Fatalf("the write-back left files beside the mock file: %v", names)
			}
		})
	}
}

// trimFinalNewline cuts the final newline off the mock file at path, and
// returns its last line.
func trimFinalNewline(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	trimmed := strings.TrimRight(string(data), "\n")
	if err := os.WriteFile(path, []byte(trimmed), 0o644); err != nil {
		t.Fatal(err)
	}
	return trimmed[strings.LastIndex(trimmed, "\n")+1:]
}

// incompleteWarnings is the WARNs that say a mock file's last mock does not
// end with a newline.
func incompleteWarnings(logs *observer.ObservedLogs) []observer.LoggedEntry {
	return logs.FilterMessageSnippet("does not end with a newline").All()
}

// sameMocks fails unless every mock in got is, encoded, byte for byte the
// recorded mock of its name: a mock is served as recorded or not at all.
func sameMocks(t *testing.T, what string, got []*models.Mock, recorded map[string][]byte) {
	t.Helper()
	for _, m := range got {
		want, ok := recorded[m.Name]
		if !ok {
			t.Fatalf("%s: served mock %q, which was not recorded", what, m.Name)
		}
		if enc := encodeForCompare(t, m); !bytes.Equal(enc, want) {
			t.Fatalf("%s: served %q changed from the recording:\n got: %s\nwant: %s", what, m.Name, enc, want)
		}
	}
}

func encodeForCompare(t *testing.T, m *models.Mock) []byte {
	t.Helper()
	doc, err := EncodeMock(m, zap.NewNop())
	if err != nil {
		t.Fatal(err)
	}
	b, err := yamlLib.Marshal(&doc)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

// readAllMocks reads the set's mocks, every pool, and its log.
func readAllMocks(t *testing.T, dir, format string) (models.TestSetMocks, []*models.Mock, *observer.ObservedLogs, error) {
	t.Helper()
	core, logs := observer.New(zapcore.DebugLevel)
	ys := NewWithFormat(zap.New(core), dir, "mocks", formatOf(format))
	set, err := ys.GetTestSetMocks(context.Background(), pruneSet, models.BaseTime, time.Now(), nil, nil)
	return set, append(append([]*models.Mock(nil), set.AllPerTest...), set.AllSession...), logs, err
}

// A last YAML document whose final line has no newline may have been cut
// short by an interrupted write, however well it parses (yaml.v3 reads almost
// any prefix of one), so it is never served: it is skipped with one WARN that
// names the file and says what to do. A file saved by hand without a final
// newline loses its last mock to this too, and the WARN says to add one. A
// rewrite moves it aside (TestARewriteMovesAnIncompleteLastMockAside); an
// NDJSON line that decodes is read, and a rewrite keeps it, with a newline.
func TestALastDocumentWithoutAFinalNewline(t *testing.T) {
	t.Run("is not read, and says so", func(t *testing.T) {
		dir := t.TempDir()
		path := writePruneFixture(t, dir, "yaml", []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2)}, "")
		if last := trimFinalNewline(t, path); !strings.HasPrefix(last, "    resTimestampMock: ") {
			t.Fatalf("precondition: the file's last line is the last mock's resTimestampMock, got %q", last)
		}
		_, got, logs, err := readAllMocks(t, dir, "yaml")
		if err != nil {
			t.Fatal(err)
		}
		if len(got) != 1 || got[0].Name != "mock-0" {
			t.Fatalf("want only mock-0 read, got %v", keysOf(byName(got)))
		}
		w := incompleteWarnings(logs)
		if len(w) != 1 || w[0].Level != zapcore.WarnLevel || w[0].ContextMap()["mock_file"] != path || w[0].ContextMap()["mock"] != "mock-1" ||
			!strings.Contains(w[0].ContextMap()["next_step"].(string), "add a final newline") {
			t.Fatalf("want one WARN naming mock-1 and %s and saying to add a final newline, got %v", path, w)
		}
		if errs := logs.FilterLevelExact(zapcore.ErrorLevel).All(); len(errs) != 0 {
			t.Fatalf("a document cut short is not an error: %v", errs)
		}
	})

	for _, format := range []string{"yaml", "json"} {
		t.Run("a rewrite/"+format, func(t *testing.T) {
			// Both end with their last line, resTimestampMock, and no newline.
			doc := strings.TrimSuffix(undecodableYAMLConnFailure, "\n")
			if format == "json" {
				doc = undecodableJSONConnFailure
			}
			dir := t.TempDir()
			path := writePruneFixture(t, dir, format, []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2)}, "")
			fh, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
			if err != nil {
				t.Fatal(err)
			}
			raw := "---\n" + doc
			if format == "json" {
				raw = doc
			}
			if _, err := fh.WriteString(raw); err != nil {
				t.Fatal(err)
			}
			if err := fh.Close(); err != nil {
				t.Fatal(err)
			}
			ys := NewWithFormat(zap.NewNop(), dir, "mocks", formatOf(format))
			consumed := map[string]models.MockState{"mock-0": {Name: "mock-0"}, "mock-1": {Name: "mock-1"}}
			if err := ys.UpdateMocks(context.Background(), pruneSet, consumed, pruneT0.Add(time.Hour), time.Time{}); err != nil {
				t.Fatalf("UpdateMocks: %v", err)
			}
			data, _ := os.ReadFile(path)
			asides, _ := filepath.Glob(path + ".incomplete-*")
			if format == "yaml" {
				// The read skipped it: moved aside as it was.
				if len(asides) != 1 || strings.Contains(string(data), doc) {
					t.Fatalf("want the document moved aside, got %v and the file\n%q", asides, data)
				}
				if aside, _ := os.ReadFile(asides[0]); string(aside) != doc {
					t.Fatalf("moved aside %q, want the document as it was", aside)
				}
			} else {
				// A whole line that decodes is read: kept as it was, with
				// the newline it lacked, so a later append starts a line.
				assertDocVerbatim(t, path, format, doc)
				if len(asides) != 0 || !strings.HasSuffix(string(data), doc+"\n") {
					t.Fatalf("want the line kept, now ending with a newline, and nothing moved aside: %v\n%q", asides, data)
				}
			}
			if n := len(decodableNames(t, dir, format)); n != 2 {
				t.Fatalf("the rewritten file must still read back: %d mocks", n)
			}
		})
	}
}

// A mock file can end part-way through its last line: the recorder was killed
// or the disk filled while appendMock wrote the last mock, which it writes in
// pieces when it is large. That never fails the set, and the cut mock is never
// served: it is skipped with one WARN naming the file, listed in Skipped when
// its name was written, and the prune and the noise write-back move it aside,
// as it was, with one WARN, and end the file at the last whole mock. A write
// that stopped inside the separator before the next mock ("-" or "--") left
// every mock before it whole: those are read, with no WARN, and a rewrite of
// the file ends it at the last of them.
func TestAnIncompleteLastMockIsNeverServed(t *testing.T) {
	type cut struct {
		name, anchor string
		n            int
		// listed is whether the cut mock's name was written, and so is in
		// Skipped.
		listed bool
	}
	cases := map[string][]cut{
		"yaml": {
			{"inside a timestamp", "resTimestampMock: ", 7, true},
			{"mid-body", "body: ", 5, true},
			{"inside a key", "    resTimestam", 0, true},
			{"inside the kind line", "\n---\nversion: api.keploy.io/v1beta1\nki", 0, false},
			// The name itself cut short is not a name to list.
			{"inside the name line", "\nname: mock-", 0, false},
			{"inside the separator, after one dash", "\n-", 0, false},
			{"inside the separator, after two dashes", "\n--", 0, false},
		},
		"json": {
			{"inside a timestamp", `"resTimestampMock":"`, 7, false},
			{"mid-body", `"body":"`, 5, false},
			{"inside a key", `"resTimestam`, 0, false},
			{"inside the kind line", `{"version":"api.keploy.io/v1beta1","ki`, 0, false},
		},
	}
	for _, format := range []string{"yaml", "json"} {
		for _, c := range cases[format] {
			t.Run(format+"/"+c.name, func(t *testing.T) {
				separator := strings.HasPrefix(c.name, "inside the separator")
				dir := t.TempDir()
				path := writePruneFixture(t, dir, format, []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2), pruneHTTPMock(3)}, "")
				_, whole, _, err := readAllMocks(t, dir, format)
				if err != nil {
					t.Fatal(err)
				}
				recorded := map[string][]byte{}
				for _, m := range whole {
					recorded[m.Name] = encodeForCompare(t, m)
				}
				data, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				anchor := c.anchor
				if separator {
					anchor = "\n---\n"
				}
				at := strings.LastIndex(string(data), anchor)
				if at < 0 {
					t.Fatalf("precondition: %q is not in the file", anchor)
				}
				end := at + len(c.anchor) + c.n
				if data[end-1] == '\n' {
					t.Fatal("precondition: the cut must fall inside a line")
				}
				// The cut mock as the read met it: its document, or its line.
				cutDoc := string(data[strings.LastIndex(string(data[:end]), "\n---\n")+5 : end])
				if format == "json" {
					cutDoc = string(data[strings.LastIndex(string(data[:end]), "\n")+1 : end])
				}
				cutFile := data[:end]

				read := func(what string, rewritten bool) {
					t.Helper()
					set, got, logs, err := readAllMocks(t, dir, format)
					if err != nil {
						t.Fatalf("%s: a mock file cut part-way through its last line failed the set: %v", what, err)
					}
					if names := keysOf(byName(got)); len(got) != 2 || byName(got)["mock-2"] != nil {
						t.Fatalf("%s: want mock-0 and mock-1 read and the cut mock-2 not, got %v", what, names)
					}
					sameMocks(t, what, got, recorded)
					if errs := logs.FilterLevelExact(zapcore.ErrorLevel).All(); len(errs) != 0 {
						t.Fatalf("%s: a mock cut short is not an error: %v", what, errs)
					}
					w := incompleteWarnings(logs)
					if separator || rewritten {
						if len(w) != 0 {
							t.Fatalf("%s: nothing incomplete is left in the file: %v", what, w)
						}
						return
					}
					if len(w) != 1 || w[0].Level != zapcore.WarnLevel || w[0].ContextMap()["mock_file"] != path {
						t.Fatalf("%s: want one WARN naming %s, got %v", what, path, w)
					}
					if _, ok := set.Skipped["mock-2"]; ok != c.listed {
						t.Fatalf("%s: Skipped = %v; the cut mock-2 listed: %v, want %v", what, set.Skipped, ok, c.listed)
					}
				}
				if err := os.WriteFile(path, cutFile, 0o644); err != nil {
					t.Fatal(err)
				}
				read("the read", false)

				for _, rewrite := range []string{"prune", "noise write-back"} {
					if err := os.WriteFile(path, cutFile, 0o644); err != nil {
						t.Fatal(err)
					}
					for _, old := range must(filepath.Glob(path + ".incomplete-*")) {
						_ = os.Remove(old)
					}
					core, logs := observer.New(zapcore.DebugLevel)
					ys := NewWithFormat(zap.New(core), dir, "mocks", formatOf(format))
					if rewrite == "prune" {
						consumed := map[string]models.MockState{"mock-0": {Name: "mock-0"}, "mock-1": {Name: "mock-1"}, "mock-2": {Name: "mock-2"}}
						if err := ys.UpdateMocks(context.Background(), pruneSet, consumed, pruneT0.Add(time.Hour), time.Time{}); err != nil {
							t.Fatalf("UpdateMocks: %v", err)
						}
					} else {
						states := map[string]models.MockState{"mock-0": {Name: "mock-0", ReqBodyNoise: map[string][]string{"body.request_id": {}}}}
						if err := ys.PersistMockNoise(context.Background(), pruneSet, states); err != nil {
							t.Fatalf("PersistMockNoise: %v", err)
						}
					}
					after, err := os.ReadFile(path)
					if err != nil {
						t.Fatal(err)
					}
					if !strings.HasSuffix(string(after), "\n") {
						t.Fatalf("the %s must end the file with a newline; it ends %q", rewrite, string(after)[max(0, len(after)-60):])
					}
					if rewrite == "noise write-back" && !strings.Contains(string(after), "body.request_id") {
						t.Fatal("precondition: the noise write-back did not rewrite the file")
					}
					asides := must(filepath.Glob(path + ".incomplete-*"))
					loud := logs.Filter(func(e observer.LoggedEntry) bool { return e.Level >= zapcore.WarnLevel }).All()
					if separator {
						if len(asides) != 0 || len(loud) != 0 {
							t.Fatalf("the %s rewrites the whole mocks before an unfinished separator and drops it, setting nothing aside: %v, %v", rewrite, asides, loud)
						}
					} else {
						if len(asides) != 1 {
							t.Fatalf("the %s must move the cut mock aside, got %v", rewrite, asides)
						}
						if got, _ := os.ReadFile(asides[0]); string(got) != cutDoc {
							t.Fatalf("the %s moved aside %q, want the cut mock as it was, %q", rewrite, got, cutDoc)
						}
						// The read already warned that it skipped the mock;
						// the rewrite says once where it put it.
						if len(loud) != 1 || loud[0].Level != zapcore.WarnLevel || loud[0].ContextMap()["mock_file"] != path || loud[0].ContextMap()["moved_to"] != asides[0] {
							t.Fatalf("want one WARN naming %s and %s, got %v", path, asides[0], loud)
						}
					}
					if rewrite == "noise write-back" {
						// It folded the learned noise into mock-0.
						_, got, _, err := readAllMocks(t, dir, format)
						if err != nil {
							t.Fatal(err)
						}
						for _, m := range got {
							if m.Name == "mock-0" {
								recorded["mock-0"] = encodeForCompare(t, m)
							}
						}
					}
					read("the read after the "+rewrite, true)
				}
			})
		}
	}
}

func must[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}

// Cutting any document of a real recording, as the file's last, at any point
// inside a line never fails the set and never serves a changed mock: every
// mock read is the recorded one, byte for byte, and the cut one is skipped
// with one WARN. A cut inside the separator before a document, or after all of
// it but its newline, leaves the one before it whole and read, with no WARN;
// so does an NDJSON line cut only of its newline. (A cut at a line boundary
// leaves a file that ends with a newline, which is read as it always was.)
//
// The last document is cut at every position, the others at every 11th, to
// keep the suite fast; KEPLOY_CUT_SWEEP_STRIDE=1 cuts every document at every
// position (about 22,000 cuts in YAML).
func TestCuttingAnyDocumentNeverServesAChangedMock(t *testing.T) {
	for _, format := range []string{"yaml", "json"} {
		t.Run(format, func(t *testing.T) {
			dir := t.TempDir()
			core, logs := observer.New(zapcore.WarnLevel)
			ys := NewWithFormat(zap.New(core), dir, "mocks", formatOf(format))
			sweepCuts(t, dir, format, func(c cutCase) {
				t.Helper()
				logs.TakeAll()
				set, err := ys.GetTestSetMocks(context.Background(), pruneSet, models.BaseTime, time.Now(), nil, nil)
				if err != nil {
					t.Fatalf("%s: the set failed: %v", c.what, err)
				}
				got := append(append([]*models.Mock(nil), set.AllPerTest...), set.AllSession...)
				sameMocks(t, c.what, got, c.recorded)
				if names := sortedNames(got); !slices.Equal(names, c.served) {
					t.Fatalf("%s: served %v, want %v", c.what, names, c.served)
				}
				want := 0
				if c.warn {
					want = 1
				}
				if n := len(incompleteWarnings(logs)); n != want {
					t.Fatalf("%s: %d incomplete WARNs, want %d; logs %v", c.what, n, want, logs.All())
				}
				if loud := logs.FilterLevelExact(zapcore.ErrorLevel).All(); len(loud) != 0 {
					t.Fatalf("%s: a cut is not an error: %v", c.what, loud)
				}
			})
		})
	}
}

// cutCase is one cut of sweepCuts: a mock file that ends part-way through a
// line.
type cutCase struct {
	what string
	// file is the cut file.
	file string
	// recorded is every mock of the file before the cut, encoded, by name.
	recorded map[string][]byte
	// served is the names, sorted, of the mocks the read serves.
	served []string
	// warn says the read skips the cut mock, with one WARN.
	warn bool
}

// sweepCuts writes, to the set in dir, every cut of a real recording in
// format and calls visit with each: each document as the file's last (after
// the one before it), cut at every point inside a line (the last document) or
// every stride-th (the others, KEPLOY_CUT_SWEEP_STRIDE, 11 by default), inside
// or at the end of the separator before it (YAML), and only of its newline
// (NDJSON).
func sweepCuts(t *testing.T, dir, format string, visit func(c cutCase)) {
	t.Helper()
	stride := 11
	if v, err := strconv.Atoi(os.Getenv("KEPLOY_CUT_SWEEP_STRIDE")); err == nil && v > 0 {
		stride = v
	}
	src, err := os.ReadFile(filepath.Join("testdata", "no_connfailure_golden", "recorded."+format))
	if err != nil {
		t.Fatal(err)
	}
	var header string
	var docs []string
	if format == "json" {
		docs = strings.Split(strings.TrimSuffix(string(src), "\n"), "\n")
	} else {
		body := string(src)
		for strings.HasPrefix(body, "#") {
			nl := strings.Index(body, "\n") + 1
			header += body[:nl]
			body = body[nl:]
		}
		docs = strings.Split(strings.TrimPrefix(body, "---\n"), "\n---\n")
		for i := range docs[:len(docs)-1] {
			docs[i] += "\n"
		}
	}
	if len(docs) < 10 {
		t.Fatalf("precondition: a recording of every kind, got %d documents", len(docs))
	}
	path := filepath.Join(dir, pruneSet, "mocks."+format)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("KEPLOY_MOCK_FORMAT", "")
	ys := NewWithFormat(zap.NewNop(), dir, "mocks", formatOf(format))
	write := func(b string) {
		if err := os.WriteFile(path, []byte(b), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	read := func(b string) []*models.Mock {
		write(b)
		set, err := ys.GetTestSetMocks(context.Background(), pruneSet, models.BaseTime, time.Now(), nil, nil)
		if err != nil {
			t.Fatal(err)
		}
		return append(append([]*models.Mock(nil), set.AllPerTest...), set.AllSession...)
	}
	cuts := 0
	for k := range docs {
		// The file: the document before (if any), then this one.
		prefix := header
		sep := ""
		if k > 0 {
			prefix += docs[k-1]
			sep = "---\n"
			if format == "json" {
				prefix, sep = docs[k-1]+"\n", ""
			}
		}
		whole := prefix + sep + docs[k]
		if format == "json" {
			whole += "\n"
		}
		recorded := map[string][]byte{}
		for _, m := range read(whole) {
			recorded[m.Name] = encodeForCompare(t, m)
		}
		var before []string
		if prefix != "" {
			before = sortedNames(read(prefix))
		}
		withCut := sortedNames(read(whole))
		if len(withCut) != len(before)+1 {
			t.Fatalf("precondition: document %d is one mock, got %v after %v", k, withCut, before)
		}
		cut := func(file string, warn, cutServed bool) {
			t.Helper()
			cuts++
			c := cutCase{what: fmt.Sprintf("document %d cut to %q", k, file[max(0, len(file)-40):]), file: file, recorded: recorded, served: before, warn: warn}
			if cutServed {
				c.served = withCut
			}
			write(file)
			visit(c)
		}
		step := stride
		if k == len(docs)-1 {
			step = 1
		}
		last := len(whole)
		if format == "json" {
			// The whole line without its newline is a whole object.
			last = len(whole) - 1
			cut(whole[:last], false, true)
		}
		for end := len(prefix) + len(sep) + 1; end < last; end += step {
			if whole[end-1] == '\n' {
				continue
			}
			cut(whole[:end], true, false)
		}
		if format == "yaml" && k > 0 {
			for _, s := range []string{"-", "--", "---", "--- "} {
				cut(prefix+s, false, false)
			}
		}
	}
	if cuts < 500 {
		t.Fatalf("precondition: want a real recording to cut, cut it %d times", cuts)
	}
	t.Logf("%d cuts", cuts)
}

func sortedNames(mocks []*models.Mock) []string {
	names := make([]string, 0, len(mocks))
	for _, m := range mocks {
		names = append(names, m.Name)
	}
	slices.Sort(names)
	return names
}

// A file that holds nothing but the start of a separator ("--": the write of
// its first mock stopped there) holds no mock: it loads empty, with no WARN, as
// nothing of a mock was written.
func TestAFileOfOnlyTheStartOfASeparatorLoadsEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, pruneSet, "mocks.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("# Generated by Keploy (3-dev)\n--"), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("KEPLOY_MOCK_FORMAT", "")
	_, got, logs, err := readAllMocks(t, dir, "yaml")
	if err != nil || len(got) != 0 || len(incompleteWarnings(logs)) != 0 {
		t.Fatalf("want no mock, no error, no WARN; got %d mocks, %v, %v", len(got), err, logs.All())
	}
}

// A file whose last NDJSON line is a whole JSON object without a newline is
// read as it is; one that is not a mock this keploy decodes is skipped as the
// cut line it may be, with the same WARN, and the set loads.
func TestAWholeLastJSONLineThatDoesNotDecodeIsSkipped(t *testing.T) {
	dir := t.TempDir()
	path := writePruneFixture(t, dir, "json", []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2)}, "")
	bad := `{"version":"api.keploy.io/v1beta1","kind":"Http","name":"mock-bad","spec":{"req":5}}`
	fh, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := fh.WriteString(bad); err != nil {
		t.Fatal(err)
	}
	if err := fh.Close(); err != nil {
		t.Fatal(err)
	}
	_, got, logs, err := readAllMocks(t, dir, "json")
	if err != nil || len(got) != 2 {
		t.Fatalf("want the two mocks read, got %d, %v", len(got), err)
	}
	w := incompleteWarnings(logs)
	if len(w) != 1 || w[0].ContextMap()["mock"] != "mock-bad" {
		t.Fatalf("want one WARN naming mock-bad, got %v", w)
	}
	// A newline would make the line fail the set (below): the WARN must not
	// suggest one.
	if step, _ := w[0].ContextMap()["next_step"].(string); step == "" || strings.Contains(step, "newline") {
		t.Fatalf("the next step for an NDJSON line that does not decode is to re-record, got %q", step)
	}
	// Control: the same line with its newline is a broken document like any
	// other, and fails the set.
	fh, err = os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := fh.WriteString("\n"); err != nil {
		t.Fatal(err)
	}
	if err := fh.Close(); err != nil {
		t.Fatal(err)
	}
	if _, _, _, err := readAllMocks(t, dir, "json"); err == nil {
		t.Fatal("control: a whole line that does not decode, with its newline, fails the set")
	}
}

// A gob mock file cut part-way through its last mock (an interrupted write)
// loads every mock before it, as gob always has, and now says, once, that the
// last one was not read.
func TestAGobFileCutPartWayThroughItsLastMockSaysSo(t *testing.T) {
	dir := t.TempDir()
	path := writePruneFixture(t, dir, "gob", []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2), pruneHTTPMock(3)}, "")
	_, _, logs, err := readAllMocks(t, dir, "yaml")
	if err != nil || len(incompleteGobWarnings(logs)) != 0 {
		t.Fatalf("control: a whole gob file reads with no WARN: %v, %v", err, logs.All())
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data[:len(data)-5], 0o644); err != nil {
		t.Fatal(err)
	}
	_, got, logs, err := readAllMocks(t, dir, "yaml")
	if err != nil || len(got) != 2 {
		t.Fatalf("want the two whole mocks read, got %d, %v", len(got), err)
	}
	if w := incompleteGobWarnings(logs); len(w) != 1 || w[0].Level != zapcore.WarnLevel || w[0].ContextMap()["mock_file"] != path {
		t.Fatalf("want one WARN naming %s, got %v", path, w)
	}
}

func incompleteGobWarnings(logs *observer.ObservedLogs) []observer.LoggedEntry {
	return logs.FilterMessageSnippet("ends part-way through its last mock").All()
}

// A rewrite (the prune, the noise write-back) of a file whose last mock the
// read skipped, because it does not end with a newline (cut short by an
// interrupted write, or saved by hand without its final newline), does not
// copy that mock: it moves it, byte for byte, to <file>.incomplete-<nanos>
// beside the file, with one WARN naming both, and the rewritten file ends with
// a newline. A file that stops in the separator after its last whole mock
// ("--") is rewritten without the dashes, and an NDJSON line the read took
// gets its newline. Either way a mock appended afterwards starts on a line of
// its own, and the set then reads every recorded mock but the skipped one,
// unchanged, and the appended one, with no WARN. (Copied as it was, an
// unfinished line would join the appended mock: the set stopped loading, or,
// when the cut fell in a line's indentation, read the separator after it and
// served the cut mock without its later fields.)
func TestARewriteMovesAnIncompleteLastMockAside(t *testing.T) {
	cases := []struct {
		name, format string
		// end damages the whole file data and returns where the moved-aside
		// mock starts (-1: nothing is moved aside).
		end func(data []byte) ([]byte, int)
	}{
		{"cut in a line's indentation", "yaml", func(d []byte) ([]byte, int) {
			at := bytes.LastIndex(d, []byte("\n    ")) + 5
			return d[:at], bytes.LastIndex(d[:at], []byte("\n---\n")) + 5
		}},
		{"cut mid-token", "yaml", func(d []byte) ([]byte, int) {
			at := bytes.LastIndex(d, []byte("resTimestampMock: ")) + len("resTimestampMock: ") + 7
			return d[:at], bytes.LastIndex(d[:at], []byte("\n---\n")) + 5
		}},
		{"a whole last line without its newline", "yaml", func(d []byte) ([]byte, int) {
			d = bytes.TrimSuffix(d, []byte("\n"))
			return d, bytes.LastIndex(d, []byte("\n---\n")) + 5
		}},
		{"-- after the last mock", "yaml", func(d []byte) ([]byte, int) {
			return append(append([]byte(nil), d...), "--"...), -1
		}},
		{"-- after a mock copied as written", "yaml", func(d []byte) ([]byte, int) {
			return append(append(append([]byte(nil), d...), "---\n"+undecodableYAMLEnterprise...), "--"...), -1
		}},
		{"cut mid-token", "json", func(d []byte) ([]byte, int) {
			at := bytes.LastIndex(d, []byte(`"resTimestampMock":"`)) + len(`"resTimestampMock":"`) + 7
			return d[:at], bytes.LastIndexByte(d[:at], '\n') + 1
		}},
		{"a whole last line without its newline", "json", func(d []byte) ([]byte, int) {
			return bytes.TrimSuffix(d, []byte("\n")), -1
		}},
	}
	for _, c := range cases {
		for _, rewrite := range []string{"prune", "noise"} {
			t.Run(c.format+"/"+c.name+"/"+rewrite+", append", func(t *testing.T) {
				dir := t.TempDir()
				path := writePruneFixture(t, dir, c.format, []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2), pruneHTTPMock(3)}, "")
				_, whole, _, err := readAllMocks(t, dir, c.format)
				if err != nil {
					t.Fatal(err)
				}
				recorded := map[string][]byte{}
				for _, m := range whole {
					recorded[m.Name] = encodeForCompare(t, m)
				}
				data, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				damaged, asideFrom := c.end(data)
				if err := os.WriteFile(path, damaged, 0o644); err != nil {
					t.Fatal(err)
				}
				want := []string{"mock-0", "mock-1", "mock-11", "mock-2"}
				if asideFrom >= 0 {
					want = []string{"mock-0", "mock-1", "mock-11"}
					delete(recorded, "mock-2")
				}

				core, logs := observer.New(zapcore.DebugLevel)
				ys := NewWithFormat(zap.New(core), dir, "mocks", formatOf(c.format))
				switch rewrite {
				case "prune":
					consumed := map[string]models.MockState{"mock-0": {Name: "mock-0"}, "mock-1": {Name: "mock-1"}, "mock-2": {Name: "mock-2"}}
					if err := ys.UpdateMocks(context.Background(), pruneSet, consumed, pruneT0.Add(time.Hour), time.Time{}); err != nil {
						t.Fatalf("UpdateMocks: %v", err)
					}
				case "noise":
					states := map[string]models.MockState{"mock-0": {Name: "mock-0", ReqBodyNoise: map[string][]string{"body.request_id": {}}}}
					if err := ys.PersistMockNoise(context.Background(), pruneSet, states); err != nil {
						t.Fatalf("PersistMockNoise: %v", err)
					}
					delete(recorded, "mock-0") // it carries the learned noise now
				}
				after, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				if !bytes.HasSuffix(after, []byte("\n")) || bytes.HasSuffix(after, []byte("--\n")) {
					t.Fatalf("the rewritten file must end with a newline, after a whole mock; it ends %q", after[max(0, len(after)-40):])
				}
				asides, _ := filepath.Glob(path + ".incomplete-*")
				moved := logs.FilterMessageSnippet("the rewrite moved it aside").All()
				if asideFrom < 0 {
					if len(asides) != 0 || len(moved) != 0 {
						t.Fatalf("the read skipped nothing, so nothing is moved aside: %v, %v", asides, moved)
					}
				} else {
					if len(asides) != 1 {
						t.Fatalf("want the skipped mock moved aside to one file, got %v", asides)
					}
					if got, _ := os.ReadFile(asides[0]); !bytes.Equal(got, damaged[asideFrom:]) {
						t.Fatalf("moved aside %q, want the skipped mock as it was, %q", got, damaged[asideFrom:])
					}
					if bytes.Contains(after, damaged[asideFrom:]) {
						t.Fatal("the skipped mock is still in the rewritten file")
					}
					if len(moved) != 1 || moved[0].Level != zapcore.WarnLevel || moved[0].ContextMap()["mock_file"] != path || moved[0].ContextMap()["moved_to"] != asides[0] {
						t.Fatalf("want one WARN naming %s and %s, got %v", path, asides[0], moved)
					}
				}

				ys.SetCounterID(10)
				if err := ys.InsertMock(context.Background(), pruneHTTPMock(4), pruneSet); err != nil {
					t.Fatalf("InsertMock: %v", err)
				}
				_, got, rlogs, err := readAllMocks(t, dir, c.format)
				if err != nil {
					t.Fatalf("the set stopped loading after the append: %v", err)
				}
				if w := rlogs.FilterLevelExact(zapcore.WarnLevel).All(); len(w) != 0 {
					t.Fatalf("the file reads whole after the append: %v", w)
				}
				if names := sortedNames(got); !slices.Equal(names, want) {
					t.Fatalf("served %v, want %v", names, want)
				}
				var unchanged []*models.Mock
				for _, m := range got {
					if _, ok := recorded[m.Name]; ok {
						unchanged = append(unchanged, m)
					}
				}
				sameMocks(t, "after the rewrite and an append", unchanged, recorded)
			})
		}
	}
}

// A rewrite that cannot move the skipped mock aside whole (the copy cannot be
// written: the disk is full), or cannot then put the rewritten file in place,
// fails, leaves no copy beside the file, and leaves the file as it was.
func TestARewriteThatCannotMoveTheMockAsideChangesNothing(t *testing.T) {
	for _, fail := range []string{"the copy", "the replace"} {
		for _, rewrite := range []string{"prune", "noise"} {
			t.Run(fail+"/"+rewrite, func(t *testing.T) {
				switch fail {
				case "the copy":
					writeAsideFile = func(name string, data []byte, perm os.FileMode) error {
						_ = os.WriteFile(name, data[:len(data)/2], perm)
						return errors.New("no space left on device")
					}
					t.Cleanup(func() { writeAsideFile = os.WriteFile })
				case "the replace":
					defer func(r func(*zap.Logger, string, string) error) { replaceFile = r }(replaceFile)
					replaceFile = func(*zap.Logger, string, string) error { return errors.New("the file is held open") }
				}
				dir := t.TempDir()
				path := writePruneFixture(t, dir, "yaml", []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2)}, "")
				data, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				cut := data[:len(data)-5]
				if err := os.WriteFile(path, cut, 0o644); err != nil {
					t.Fatal(err)
				}
				ys := NewWithFormat(zap.NewNop(), dir, "mocks", yaml.FormatYAML)
				if rewrite == "prune" {
					err = ys.UpdateMocks(context.Background(), pruneSet, nil, time.Time{}, time.Time{})
				} else {
					err = ys.PersistMockNoise(context.Background(), pruneSet, map[string]models.MockState{"mock-0": {Name: "mock-0", ReqBodyNoise: map[string][]string{"body.request_id": {}}}})
				}
				if err == nil {
					t.Fatalf("want the %s to fail when %s fails", rewrite, fail)
				}
				if asides, _ := filepath.Glob(path + ".incomplete-*"); len(asides) != 0 {
					t.Fatalf("a copy was left beside the file: %v", asides)
				}
				if after, _ := os.ReadFile(path); !bytes.Equal(after, cut) {
					t.Fatal("the file changed")
				}
			})
		}
	}
}

// Only the file's last document may be incomplete: a write is interrupted at
// the end of the file. A document that does not parse before it is damage, and
// still fails the set rather than being read around.
func TestABrokenDocumentBeforeTheLastStillFailsTheSet(t *testing.T) {
	t.Run("yaml, before an unfinished separator", func(t *testing.T) {
		// The document before "--" is complete, so it is read as any
		// other: one that does not parse fails the set.
		dir := t.TempDir()
		path := writePruneFixture(t, dir, "yaml", []*models.Mock{pruneHTTPMock(1)}, "")
		fh, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := fh.WriteString("---\nversion: api.keploy.io/v1beta1\nkind: Http\nname: mock-broken\nspec: {req: [\n--"); err != nil {
			t.Fatal(err)
		}
		if err := fh.Close(); err != nil {
			t.Fatal(err)
		}
		if _, _, _, err := readAllMocks(t, dir, "yaml"); err == nil {
			t.Fatal("a document that does not parse, before an unfinished separator, must fail the set")
		}
	})
	for _, format := range []string{"yaml", "json"} {
		t.Run(format, func(t *testing.T) {
			broken := "---\nversion: api.keploy.io/v1beta1\nkind: Http\nname: mock-broken\nspec: {req: [\n"
			if format == "json" {
				broken = `{"version":"api.keploy.io/v1beta1","kind":"Http","name":"mock-broken","spec":{` + "\n"
			}
			dir := t.TempDir()
			writePruneFixture(t, dir, format, []*models.Mock{pruneHTTPMock(1), pruneHTTPMock(2)}, broken)
			ys := NewWithFormat(zap.NewNop(), dir, "mocks", formatOf(format))
			if _, err := ys.GetTestSetMocks(context.Background(), pruneSet, models.BaseTime, time.Now(), nil, nil); err == nil {
				t.Fatal("a document that does not parse, before the last, must fail the set")
			}
		})
	}
}
