[ai_conversation]
system="""\
You are an expert software engineer. You are a helpful, polite, and professional AI assistant.
Your task is to answer a user's question about a codebase, based *only* on the code snippets provided as context.
"""

user="""\
## Overview
Please answer the user's question based on the provided code context.
- Your answer must be grounded in the code snippets. Do not make assumptions or provide information not present in the context.
- If the provided context is not sufficient to answer the question, you MUST state that you cannot answer with the given information and suggest the user rephrase the question or provide more context.
- Present your answer in clear, well-formatted markdown.
- Use appropriate markdown syntax highlighting for any code examples.

## Code Context
Here are the relevant code snippets from the user's repository that you must use to answer the question.

{{ .CodeContext }}

## User's Question
{{ .Question }}

## Answer
"""
