package mapdb

import (
	"bytes"
	"context"
	"path/filepath"

	"go.keploy.io/server/v3/pkg/models"
	"go.keploy.io/server/v3/pkg/platform/yaml"
	"go.keploy.io/server/v3/utils"
	"go.uber.org/zap"
)

// ReplaceRow sets one test's mock entries EXACTLY, replacing whatever is on
// disk for that test instead of unioning with it. Other tests, and the startup
// section, are left untouched.
//
// Upsert deliberately cannot do this: its mergeMockEntries unions by mock name
// ("union, never replace") because a test's mapping arrives from the agent in
// several deltas during recording, and overwriting on a later delta would drop
// the mocks an earlier one recorded.
//
// Replacing a single recorded test case needs the opposite. The replacement
// reuses the freed mock names, so a union sees them as duplicates and keeps the
// STALE entries — leaving the row pointing at the old mocks' timestamps while
// the mocks file holds the new ones. The replayer then finds no candidate
// mock inside the case's window and the test replays with none.
//
// Passing no entries clears the test's row rather than deleting the test from
// the mapping, which keeps "this test consumes nothing" distinguishable from
// "this test was never mapped".
func (db *MappingDb) ReplaceRow(ctx context.Context, testSetID string, testID string, entries []models.MockEntry) error {
	mappingPath := filepath.Join(db.path, testSetID)
	fileName := db.MapFileName
	if fileName == "" {
		fileName = "mappings"
	}

	exists, detected, err := yaml.FileExistsAny(ctx, db.logger, mappingPath, fileName, db.Format)
	if err != nil {
		utils.LogError(db.logger, err, "failed to check if mapping file exists",
			zap.String("path", mappingPath), zap.String("fileName", fileName))
		return err
	}

	effFormat := db.Format
	var mapping *models.Mapping
	var leadingComment []byte

	if exists {
		effFormat = detected
		fileData, err := yaml.ReadFileF(ctx, db.logger, mappingPath, fileName, effFormat)
		if err != nil {
			utils.LogError(db.logger, err, "failed to read mapping file for replace",
				zap.String("testSetID", testSetID))
			return err
		}
		// Carry the "# Generated by Keploy (...)" header across the rewrite.
		// The encoder does not emit it, and UpsertBatch only re-adds it when
		// creating the file, so an in-place rewrite would silently drop it and
		// show up as a spurious deletion in every diff.
		leadingComment = leadingCommentOf(fileData, effFormat)

		mapping, err = DecodeMappingF(fileData, db.logger, effFormat)
		if err != nil {
			utils.LogError(db.logger, err, "failed to decode mapping",
				zap.String("testSetID", testSetID))
			return err
		}
	} else {
		mapping = &models.Mapping{
			Version:   string(models.V1Beta1),
			Kind:      models.MappingKind,
			TestSetID: testSetID,
			TestCases: []models.MappedTestCase{},
		}
		if effFormat == yaml.FormatYAML {
			leadingComment = []byte(utils.GetVersionAsComment())
		}
	}

	replaced := false
	for i := range mapping.TestCases {
		if mapping.TestCases[i].ID == testID {
			mapping.TestCases[i].Mocks = entries
			replaced = true
			break
		}
	}
	if !replaced {
		mapping.TestCases = append(mapping.TestCases, models.MappedTestCase{
			ID:    testID,
			Mocks: entries,
		})
	}

	encoded, err := EncodeMappingF(mapping, db.logger, effFormat)
	if err != nil {
		utils.LogError(db.logger, err, "failed to encode mapping during replace",
			zap.String("testSetID", testSetID))
		return err
	}
	if len(leadingComment) > 0 {
		encoded = append(leadingComment, encoded...)
	}

	if err := yaml.WriteFileF(ctx, db.logger, mappingPath, fileName, encoded, false, effFormat); err != nil {
		utils.LogError(db.logger, err, "failed to write mapping file during replace",
			zap.String("testSetID", testSetID))
		return err
	}

	db.logger.Debug("replaced test-mock mapping row",
		zap.String("testSetID", testSetID),
		zap.String("testID", testID),
		zap.Int("entries", len(entries)))

	return nil
}

// leadingCommentOf returns the run of leading "#" comment lines at the top of a
// YAML document, including their trailing newline. JSON has no comments, so it
// always returns nil for that format.
func leadingCommentOf(data []byte, format yaml.Format) []byte {
	if format != yaml.FormatYAML {
		return nil
	}
	var out []byte
	rest := data
	for len(rest) > 0 && rest[0] == '#' {
		idx := bytes.IndexByte(rest, '\n')
		if idx < 0 {
			out = append(out, rest...)
			break
		}
		out = append(out, rest[:idx+1]...)
		rest = rest[idx+1:]
	}
	return out
}
