package mapdb

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.keploy.io/server/v3/pkg/models"
	"go.uber.org/zap"
)

func entry(name, req string) models.MockEntry {
	return models.MockEntry{Name: name, Kind: "Mongo", ReqTimestampMock: req}
}

func readRow(t *testing.T, db *MappingDb, set, testID string) []models.MockEntry {
	t.Helper()
	byTest, _, err := db.Get(context.Background(), set)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	return byTest[testID]
}

// The bug this exists for: Upsert unions by mock name, so replacing a case
// whose new mocks REUSE the freed names silently keeps the stale entries.
func TestReplaceRow_ReplacesEntriesThatReuseTheSameNames(t *testing.T) {
	dir := t.TempDir()
	db := New(zap.NewNop(), dir, "")
	ctx := context.Background()

	if err := db.Upsert(ctx, "set", "case-1", []models.MockEntry{entry("mock-5", "OLD")}); err != nil {
		t.Fatal(err)
	}

	// Upsert cannot do it — same name, so the union keeps the stale entry.
	if err := db.Upsert(ctx, "set", "case-1", []models.MockEntry{entry("mock-5", "NEW")}); err != nil {
		t.Fatal(err)
	}
	if got := readRow(t, db, "set", "case-1"); got[0].ReqTimestampMock != "OLD" {
		t.Fatalf("precondition changed: Upsert now replaces (%q); this test guards ReplaceRow's reason to exist", got[0].ReqTimestampMock)
	}

	if err := db.ReplaceRow(ctx, "set", "case-1", []models.MockEntry{entry("mock-5", "NEW")}); err != nil {
		t.Fatal(err)
	}
	got := readRow(t, db, "set", "case-1")
	if len(got) != 1 || got[0].ReqTimestampMock != "NEW" {
		t.Errorf("row = %+v, want a single entry with the NEW timestamp", got)
	}
}

func TestReplaceRow_LeavesOtherTestsAlone(t *testing.T) {
	dir := t.TempDir()
	db := New(zap.NewNop(), dir, "")
	ctx := context.Background()

	if err := db.UpsertBatch(ctx, "set", map[string][]models.MockEntry{
		"case-1": {entry("mock-1", "A")},
		"case-2": {entry("mock-2", "B")},
	}); err != nil {
		t.Fatal(err)
	}

	if err := db.ReplaceRow(ctx, "set", "case-1", []models.MockEntry{entry("mock-9", "Z")}); err != nil {
		t.Fatal(err)
	}

	if got := readRow(t, db, "set", "case-1"); len(got) != 1 || got[0].Name != "mock-9" {
		t.Errorf("case-1 = %+v", got)
	}
	if got := readRow(t, db, "set", "case-2"); len(got) != 1 || got[0].Name != "mock-2" || got[0].ReqTimestampMock != "B" {
		t.Errorf("case-2 was disturbed: %+v", got)
	}
}

func TestReplaceRow_AddsTheTestWhenAbsent(t *testing.T) {
	dir := t.TempDir()
	db := New(zap.NewNop(), dir, "")
	ctx := context.Background()

	if err := db.ReplaceRow(ctx, "set", "case-new", []models.MockEntry{entry("mock-0", "X")}); err != nil {
		t.Fatal(err)
	}
	if got := readRow(t, db, "set", "case-new"); len(got) != 1 || got[0].Name != "mock-0" {
		t.Errorf("row = %+v", got)
	}
}

func TestReplaceRow_EmptyEntriesClearTheRowWithoutRemovingTheTest(t *testing.T) {
	dir := t.TempDir()
	db := New(zap.NewNop(), dir, "")
	ctx := context.Background()

	if err := db.Upsert(ctx, "set", "case-1", []models.MockEntry{entry("mock-1", "A")}); err != nil {
		t.Fatal(err)
	}
	if err := db.ReplaceRow(ctx, "set", "case-1", nil); err != nil {
		t.Fatal(err)
	}

	byTest, _, err := db.Get(ctx, "set")
	if err != nil {
		t.Fatal(err)
	}
	entries, present := byTest["case-1"]
	if !present {
		t.Error("the test should still be present in the mapping, with an empty row")
	}
	if len(entries) != 0 {
		t.Errorf("row should be empty, got %+v", entries)
	}
}

// An in-place rewrite must not drop the "# Generated by Keploy" header.
// UpsertBatch only prepends it when CREATING the file, so a rewrite through
// that path loses it and every diff shows a spurious deletion.
func TestReplaceRow_PreservesTheVersionHeader(t *testing.T) {
	dir := t.TempDir()
	db := New(zap.NewNop(), dir, "")
	ctx := context.Background()
	path := filepath.Join(dir, "set", "mappings.yaml")

	if err := db.Upsert(ctx, "set", "case-1", []models.MockEntry{entry("mock-1", "A")}); err != nil {
		t.Fatal(err)
	}
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(before), "#") {
		t.Skip("this build writes no version header; nothing to preserve")
	}

	if err := db.ReplaceRow(ctx, "set", "case-1", []models.MockEntry{entry("mock-1", "B")}); err != nil {
		t.Fatal(err)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(after), "#") {
		t.Errorf("the version header was dropped by the rewrite:\n%s", after)
	}
}
