package testdb

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
	"time"

	"go.keploy.io/server/v3/pkg/models"
	"go.keploy.io/server/v3/pkg/platform/yaml"
	"go.uber.org/zap"
)

// Backward-compatibility pin for the consumer contract.
//
// Adding models.CONSUMER touches four switches in util.go, one in naming.go
// and two in db.go, every one of them by INSERTING an arm before an existing
// default. The claim that no existing kind changed is only worth anything if
// something checks it, so these fixtures are encoded through the real
// EncodeTestcase / EncodeTestcaseJSON and compared byte-for-byte against files
// GENERATED BY THE PRE-CONSUMER BUILD (commit 8181969). Regenerating them from
// the post-change code would make the test vacuous, which is why the update
// flag exists but the checked-in bytes came from the old tree.
//
// The four files this test reads — http-testcase.{yaml,json} and
// grpc-testcase.{yaml,json} — are the ONLY compatibility goldens in that
// directory. testdata/consumer-testcase.{yaml,json} could not be generated by
// the pre-consumer build because they describe a schema that did not exist
// there; they are a forward schema pin owned by TestConsumerTestCaseSchemaIsPinned
// in consumer_test.go, and they prove nothing about backward compatibility.
//
// To regenerate deliberately (only when a schema change is intended and
// reviewed):
//
//	go test ./pkg/platform/yaml/testdb/... -run TestExistingKinds -update-golden
var updateGolden = flag.Bool("update-golden", false, "rewrite the testdata/*-testcase.{yaml,json} goldens from the fixtures")

const (
	goldenHTTPYAML = "testdata/http-testcase.yaml"
	goldenHTTPJSON = "testdata/http-testcase.json"
	goldenGRPCYAML = "testdata/grpc-testcase.yaml"
	goldenGRPCJSON = "testdata/grpc-testcase.json"
)

func goldenLogger(t *testing.T) *zap.Logger {
	t.Helper()
	return zap.NewNop()
}

// httpFixture is a recorded HTTP test case with everything an encoder touches:
// headers, a JSON body, url params, a curl, user noise, a description and an
// app port.
func httpFixture() models.TestCase {
	ts := time.Date(2026, 8, 22, 10, 0, 0, 0, time.UTC)
	return models.TestCase{
		Version:     models.V1Beta1,
		Kind:        models.HTTP,
		Name:        "test-1",
		Description: "fetch one order",
		Created:     1755861852,
		Curl:        "curl --request GET --url http://localhost:8080/orders/1",
		HTTPReq: models.HTTPReq{
			Method: "GET", ProtoMajor: 1, ProtoMinor: 1,
			URL:       "http://localhost:8080/orders/1",
			URLParams: map[string]string{"expand": "items"},
			Header:    map[string]string{"Accept": "application/json"},
			Body:      "",
			Timestamp: ts,
		},
		HTTPResp: models.HTTPResp{
			StatusCode:    200,
			Header:        map[string]string{"Content-Type": "application/json"},
			Body:          `{"id":1,"status":"CONFIRMED","total":41.97}`,
			StatusMessage: "OK",
			ProtoMajor:    1, ProtoMinor: 1,
			Timestamp: ts.Add(12 * time.Millisecond),
		},
		Noise:      map[string][]string{"body.total": {}},
		Assertions: map[models.AssertionType]interface{}{},
		AppPort:    8080,
	}
}

// grpcFixture is a recorded gRPC test case with pseudo headers, ordinary
// headers, trailers and user noise.
func grpcFixture() models.TestCase {
	ts := time.Date(2026, 8, 22, 10, 1, 0, 0, time.UTC)
	return models.TestCase{
		Version: models.V1Beta1,
		Kind:    models.GRPC_EXPORT,
		Name:    "test-2",
		Created: 1755861853,
		GrpcReq: models.GrpcReq{
			Headers: models.GrpcHeaders{
				PseudoHeaders:   map[string]string{":path": "/orders.OrderService/GetOrder", ":method": "POST"},
				OrdinaryHeaders: map[string]string{"content-type": "application/grpc"},
			},
			Body:      models.GrpcLengthPrefixedMessage{CompressionFlag: 0, MessageLength: 7, DecodedData: `{"id":1}`},
			Timestamp: ts,
		},
		GrpcResp: models.GrpcResp{
			Headers: models.GrpcHeaders{
				PseudoHeaders:   map[string]string{":status": "200"},
				OrdinaryHeaders: map[string]string{"content-type": "application/grpc"},
			},
			Body:      models.GrpcLengthPrefixedMessage{CompressionFlag: 0, MessageLength: 21, DecodedData: `{"status":"CONFIRMED"}`},
			Trailers:  models.GrpcHeaders{OrdinaryHeaders: map[string]string{"grpc-status": "0"}},
			Timestamp: ts.Add(9 * time.Millisecond),
		},
		Noise:      map[string][]string{"grpcResp.body.decoded_data.processedAt": {}},
		Assertions: map[models.AssertionType]interface{}{},
		AppPort:    9090,
	}
}

// encodeBoth returns the YAML and JSON on-disk bytes for a test case, through
// exactly the code paths the recorder uses.
func encodeBoth(t *testing.T, tc models.TestCase) (yamlBytes, jsonBytes []byte) {
	t.Helper()
	log := goldenLogger(t)

	doc, err := EncodeTestcase(tc, log)
	if err != nil {
		t.Fatalf("EncodeTestcase(%s): %v", tc.Kind, err)
	}
	yamlBytes, err = yaml.MarshalDoc(yaml.FormatYAML, doc)
	if err != nil {
		t.Fatalf("MarshalDoc yaml: %v", err)
	}

	jsonDoc, err := EncodeTestcaseJSON(tc, log)
	if err != nil {
		t.Fatalf("EncodeTestcaseJSON(%s): %v", tc.Kind, err)
	}
	jsonBytes, err = json.MarshalIndent(jsonDoc, "", "  ")
	if err != nil {
		t.Fatalf("marshal json doc: %v", err)
	}
	jsonBytes = append(jsonBytes, '\n')
	return yamlBytes, jsonBytes
}

func compareGolden(t *testing.T, path string, got []byte) {
	t.Helper()
	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
		t.Logf("regenerated %s (%d bytes)", path, len(got))
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (regenerate with -update-golden ONLY if the change is intended)", path, err)
	}
	if string(got) != string(want) {
		t.Fatalf("%s changed.\nThese bytes are a checked-in on-disk contract: an existing kind must not change\nhow it serializes, and the consumer schema is hand-editable and written by a\nparser in another repository. Regenerate with -update-golden ONLY when the\nschema change is intended and reviewed.\n--- on disk ---\n%s\n--- produced now ---\n%s", path, want, got)
	}
}

// The whole backward-compatibility claim in one test: an HTTP and a gRPC test
// case must serialize to exactly the bytes the pre-consumer build produced, in
// both storage formats.
func TestExistingKindsSerializeByteIdentically(t *testing.T) {
	httpYAML, httpJSON := encodeBoth(t, httpFixture())
	compareGolden(t, goldenHTTPYAML, httpYAML)
	compareGolden(t, goldenHTTPJSON, httpJSON)

	grpcYAML, grpcJSON := encodeBoth(t, grpcFixture())
	compareGolden(t, goldenGRPCYAML, grpcYAML)
	compareGolden(t, goldenGRPCJSON, grpcJSON)
}

// And the decode side: the checked-in bytes must decode into the same
// TestCase, then re-encode to the same bytes. This is what catches a decode
// arm that accidentally consumes a field an existing kind needs.
func TestExistingKindsRoundTripThroughDecode(t *testing.T) {
	log := goldenLogger(t)
	cases := []struct {
		name     string
		yamlPath string
		jsonPath string
	}{
		{"http", goldenHTTPYAML, goldenHTTPJSON},
		{"grpc", goldenGRPCYAML, goldenGRPCJSON},
	}
	for _, c := range cases {
		t.Run(c.name+"/yaml", func(t *testing.T) {
			raw, err := os.ReadFile(c.yamlPath)
			if err != nil {
				t.Fatalf("read: %v", err)
			}
			doc, err := yaml.UnmarshalDoc(yaml.FormatYAML, raw)
			if err != nil {
				t.Fatalf("UnmarshalDoc: %v", err)
			}
			tc, err := Decode(doc, log)
			if err != nil {
				t.Fatalf("Decode: %v", err)
			}
			again, err := EncodeTestcase(*tc, log)
			if err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			out, err := yaml.MarshalDoc(yaml.FormatYAML, again)
			if err != nil {
				t.Fatalf("re-marshal: %v", err)
			}
			if string(out) != string(raw) {
				t.Fatalf("%s did not survive decode->encode.\n--- in ---\n%s\n--- out ---\n%s", c.yamlPath, raw, out)
			}
		})
		t.Run(c.name+"/json", func(t *testing.T) {
			raw, err := os.ReadFile(c.jsonPath)
			if err != nil {
				t.Fatalf("read: %v", err)
			}
			var jsonDoc yaml.NetworkTrafficDocJSON
			if err := json.Unmarshal(raw, &jsonDoc); err != nil {
				t.Fatalf("unmarshal: %v", err)
			}
			tc, err := DecodeJSON(&jsonDoc, log)
			if err != nil {
				t.Fatalf("DecodeJSON: %v", err)
			}
			again, err := EncodeTestcaseJSON(*tc, log)
			if err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			out, err := json.MarshalIndent(again, "", "  ")
			if err != nil {
				t.Fatalf("re-marshal: %v", err)
			}
			out = append(out, '\n')
			if string(out) != string(raw) {
				t.Fatalf("%s did not survive decode->encode.\n--- in ---\n%s\n--- out ---\n%s", c.jsonPath, raw, out)
			}
		})
	}
}
