name: Build Keploy Binary

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build binary
        run: go build -tags=viper_bind_struct -cover -o keployB

      - name: Upload Keploy Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keploy-binary
          path: keployB

# Add Jobs for testing different applications here.          
  test-go-mongo-1:
    needs: build
    uses: ./.github/workflows/test-go-mongo-1.yml 

  test-go-mongo-2:
    needs: build
    uses: ./.github/workflows/test-go-mongo-2.yml    


# Wait for all the test workflows before getting the coverage
  get-coverage:
    needs: [test-go-mongo-1, test-go-mongo-2]
    uses: ./.github/workflows/coverage_stage.yml     

#https://github.com/marketplace/actions/delete-artifact