name: KeployAI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: [selfhosted-linux-amd64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Smart AI Code Review
        uses: euclidstellar/code-review-agent@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}