name: MySQL-Golang On Linux
on: [pull_request]
jobs:
  mysql_golang_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build binary
      run: |
        go build -race -tags=viper_bind_struct -o keployv2
    - name: Checkout the samples-go repository
      uses: actions/checkout@v4
      with:
        repository: keploy/samples-go
        path: samples-go
    - name: Run echo-mysql application
      run: |
        cd samples-go/echo-mysql
        source ./../../.github/workflows/test_workflow_scripts/golang-mysql-linux.sh