name: gRPC Fuzzer

on:
  workflow_call:
    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  grpc_fuzzer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # incoming mode
          - job: incoming_record_latest_replay_build
            mode: incoming
            record_src: latest
            replay_src: build
          - job: incoming_record_build_replay_latest
            mode: incoming
            record_src: build
            replay_src: latest
          - job: incoming_record_build_replay_build
            mode: incoming
            record_src: build
            replay_src: build
          # outgoing mode
          - job: outgoing_record_latest_replay_build
            mode: outgoing
            record_src: latest
            replay_src: build
          - job: outgoing_record_build_replay_latest
            mode: outgoing
            record_src: build
            replay_src: latest
          - job: outgoing_record_build_replay_build
            mode: outgoing
            record_src: build
            replay_src: build

    name: ${{ matrix.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: record
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.record_src }}

      - id: replay
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.replay_src }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Download and Extract gRPC Fuzzer
        id: fuzzer
        run: |
          set -euo pipefail
          KEY="releases/grpc-fuzzer/latest/grpc-fuzzer-linux-amd64.tar.gz"
          aws s3 cp "s3://${{ vars.AWS_S3_BUCKET }}/${KEY}" .
          tar -xzf grpc-fuzzer-linux-amd64.tar.gz
          chmod +x ./client ./server
          echo "client=$(realpath ./client)" >> $GITHUB_OUTPUT
          echo "server=$(realpath ./server)" >> $GITHUB_OUTPUT

      - name: Run gRPC Fuzzer test
        env:
          RECORD_BIN: ${{ steps.record.outputs.path }}
          REPLAY_BIN: ${{ steps.replay.outputs.path }}
          FUZZER_CLIENT_BIN: ${{ steps.fuzzer.outputs.client }}
          FUZZER_SERVER_BIN: ${{ steps.fuzzer.outputs.server }}
        run: |
          SCRIPT_PATH="$GITHUB_WORKSPACE/.github/workflows/test_workflow_scripts/fuzzer/grpc/golang-linux.sh"
          chmod +x "$SCRIPT_PATH"
          source "$SCRIPT_PATH" ${{ matrix.mode }}