name: MySQL Fuzzer On Linux
on:
  workflow_call:

jobs:
  mysql_fuzzer_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - job: record_latest_replay_build
            record_src: latest
            replay_src: build
          - job: record_build_replay_latest
            record_src: build
            replay_src: latest
          - job: record_build_replay_build
            record_src: build
            replay_src: build
    name: ${{ matrix.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: record
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.record_src }}

      - id: replay
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.replay_src }}
      
      - name: Print Variables for Debugging
        run: |
          echo "AWS Access Key ID: ${{ vars.AWS_ACCESS_KEY_ID }}"
          echo "AWS Region: ${{ vars.AWS_DEFAULT_REGION }}"
          echo "AWS S3 Bucket: ${{ vars.AWS_S3_BUCKET }}"


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: "sjfdlaksf"
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Download and Extract Fuzzer
        id: fuzzer
        run: |
          set -e
          aws s3 cp s3://${{ vars.AWS_S3_BUCKET }}/releases/mysql-fuzzer/latest/mysql-fuzzer-linux-amd64.tar.gz .
          tar -xzf mysql-fuzzer-linux-amd64.tar.gz
          chmod +x ./mysql-fuzzer
          echo "path=$(realpath ./mysql-fuzzer)" >> $GITHUB_OUTPUT

      - name: Run MySQL Fuzzer Test
        env:
          FUZZER_BIN: ${{ steps.fuzzer.outputs.path }}
          RECORD_BIN: ${{ steps.record.outputs.path }}
          REPLAY_BIN: ${{ steps.replay.outputs.path }}
        run: |
          cd samples-go/echo-mysql
          source ./../../.github/workflows/test_workflow_scripts/mysql-fuzzer-linux.sh
