name: Python On Docker (Windows)

on:
  workflow_call:
    inputs:
      image_ref:
        description: "Docker image to pull (e.g., ttl.sh/keploy/keploy-win-<sha>:1h)"
        required: true
        type: string

jobs:
  python_docker_windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        app: 
          - name: flask-mongo
            path: flask-mongo
            script_dir: flask-mongo
        config:
          - job: record_latest_replay_build
            record_src: latest
            replay_src: build
          - job: record_build_replay_latest
            record_src: build
            replay_src: latest
          - job: record_build_replay_build
            record_src: build
            replay_src: build

    name: ${{ matrix.app.name }} (${{ matrix.config.job }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        env:
          LIMA_START_ARGS: --cpus 4 --memory 8

      - name: Pull test image (from build job)
        shell: bash
        run: |
          echo "Pulling ${{ inputs.image_ref }}"
          docker pull "${{ inputs.image_ref }}"
          # Optional: retag to the name your scripts expect
          docker tag "${{ inputs.image_ref }}" ghcr.io/keploy/keploy:v2-dev
          docker images | head -n 20

      - id: record
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.config.record_src }}

      - id: replay
        uses: ./.github/actions/download-binary
        with:
          src: ${{ matrix.config.replay_src }}

      - name: Checkout the samples-python repository
        uses: actions/checkout@v4
        with:
          repository: keploy/samples-python
          path: samples-python

      - name: Run ${{ matrix.app.name }} application
        env:
          RECORD_BIN: ${{ steps.record.outputs.path }}
          REPLAY_BIN: ${{ steps.replay.outputs.path }}
        shell: bash
        run: |
          cd samples-python/${{ matrix.app.path }}
          bash $GITHUB_WORKSPACE/.github/workflows/test_workflow_scripts/python/${{ matrix.app.script_dir }}/python-docker-windows.sh
