name: Release
on:
  push:
    tags:
    - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
#  build-ui:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version-file: go.mod

#      - name: Checkout UI
#        uses: actions/checkout@v4
#        with:
#          repository: keploy/ui
#          path: ui
#
#      - name: Cache UI
#        id: cache-ui
#        uses: actions/cache@v3
#        with:
#          path: web
#          key: ${{ hashFiles('ui/src') }}
#
#      - name: Set up Node
#        if: steps.cache-ui.outputs.cache-hit != 'true'
#        uses: actions/setup-node@v3
#        with:
#          node-version: '14'
#
#      - name: Build web app
#        if: steps.cache-ui.outputs.cache-hit != 'true'
#        run: |
#          cd $GITHUB_WORKSPACE/ui
#          npm install
#          npm run build
#          cp -r public $GITHUB_WORKSPACE/web
#          rm -rf $GITHUB_WORKSPACE/ui

  build-go:
    runs-on: macos-latest
    # runs-on: ubuntu-latest
#    needs: build-ui
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Private Parsers
        uses: ./.github/actions/setup-private-parsers
        with:
          ssh-private-key: ${{ secrets.INTEGRATIONS_REPO_DEPLOY_KEY_PRIVATE }}
          go-cache: true

#      - name: Checkout UI
#        uses: actions/checkout@v4
#        with:
#          repository: keploy/ui
#          path: ui
#
#      - name: Cache UI
#        id: cache-ui
#        uses: actions/cache@v3
#        with:
#          path: web
#          key: ${{ hashFiles('ui/src') }}
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v5
        with:
          # The certificates in a PKCS12 file encoded as a base64 string created with "openssl base64 -in cert.p12 -out cert-base64.txt"
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name:  Install gon for code signing and app notarization
        run: |
          wget -q https://github.com/Bearer/gon/releases/download/v0.0.37/gon_macos.zip
          unzip gon_macos.zip -d /usr/local/bin
          rm -rf gon_macos.zip

      - name: Install cross-compilation tools
        run: |
          brew install mingw-w64
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v1.26.2
          args: release --rm-dist --skip-validate
        env:
          AC_PROVIDER: ${{ secrets.APPLE_ACCOUNT_TEAM_ID }}
          AC_PASSWORD: ${{ secrets.APPLE_ACCOUNT_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_DSN_BINARY: ${{ secrets.SENTRY_DSN_BINARY }}
          GITTHUB_APP_CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB_APP }}
          SERVER_URL: https://api.keploy.io

  build-docker:
    needs: build-go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Private Parsers
        uses: ./.github/actions/setup-private-parsers
        with:
          ssh-private-key: ${{ secrets.INTEGRATIONS_REPO_DEPLOY_KEY_PRIVATE }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ghcr.io
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set version
        shell: bash
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV

      - name: Prepare Dockerfile for Release Build
        run: |
          sed -i '/COPY go.mod go.sum \/app\//a RUN git config --global url."ssh:\/\/git@github.com\/".insteadOf "https:\/\/github.com\/" \&\& mkdir -p -m 0700 ~\/.ssh \&\& ssh-keyscan github.com >> ~\/.ssh\/known_hosts' ./Dockerfile
          sed -i 's/RUN go mod download/RUN --mount=type=ssh go mod download/' ./Dockerfile

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          ssh: default
          platforms: linux/amd64, linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SENTRY_DSN_DOCKER=${{ secrets.SENTRY_DSN_DOCKER }}
            VERSION=${{ env.VERSION }}
            SERVER_URL=https://api.keploy.io
            GITTHUB_APP_CLIENT_ID=${{ secrets.CLIENT_ID_GITHUB_APP }}

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes ghcr.io/${{ github.repository }}@${{ steps.build-and-push.outputs.digest }}

  mark-latest:
    needs: [build-go, build-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Mark release as latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --latest
